### ISSUE TITLE
Removing a layer in a macro

### ISSUE THREAD

**Issue by promisedlandt** [david-janssen/kmonad#11]
Hello,

I want to support the following workflow:

- press a trigger key to enter e.g. desktop switching mode
- press another key to do the action I want (e.g. switch to desktop 1) and exit desktop switching mode

The first point is easy with a layer - I have `@ds = LA-ds`. But I'm stuck on the second point. `@ds1 = (( M-w 1 ))` works for the switching part, but adding `@ds1 = (( M-w 1 LR-ds ))` leads to a syntax error.

Is it possible to somehow remove a layer in a macro? Or do you have another suggestion on how to solve the issue?

**Comment by david-janssen** [comment]
Hey there,

That is currently a feature we don't support, but definitely a feature we should support. I'll put it on the top of my list and let you know when it's implemented. Let's leave this open until I do.

**Comment by promisedlandt** [comment]
Great to hear! I was very happy when I found out kmonad existed.

**Comment by david-janssen** [comment]
Sooooo:

Turns out I remember why I didn't add support for this originally. It's because at the moment the internal representation of actions is a bit muddled, and we make a slightly artificial distinction between internal button-events and output key-events. That is to say: a macro translates 1 input-press into a series of output presses. However, switching a layer isn't an output press, it's an internal action. This makes it impossible to do in a macro (currently, I want to refactor this soon, see #13).

I didn't want to leave you hanging though, because the concept of sequencing actions is very simple and well supported, just not in macros. So, I added a new button-type, the 'After' button, that allows you to arbitrarily sequence actions that can be triggered by tapping buttons. See [the syntax guide](doc/syntax_guide.md#sequencing-actions) for an overview of how to use them.

Do you have a haskell environment setup? Because then simply pulling and compiling should do it. If now, let me know, and I can make a little mini-release with a statically compiled binary so you can try the new functionality.

I'm going to leave this open for now, because it points at something that hasn't been fixed yet: More powerful macros. Ideally you'd be able to just use the syntax that seemed intuitive to you. When I do figure that out I'll close this issue.

**Comment by promisedlandt** [comment]
It works perfectly, and was easy to compile because you already included instructions in the README.

Thank you very much for your time and effort!

**Comment by david-janssen** [comment]
Since the original issue was resolved I left this open because I wanted a reminder about implementing more powerful macros. I've taken that idea and started implementing something related to it. I am going to close this issue now to keep the issues folder tidy.
