### ISSUE TITLE
Mappings for F13 to F24 seem to be wrong

### ISSUE THREAD

**Issue by stevep99** [david-janssen/kmonad#121]
Putting any the functions keys f1 to f12 in your deflayer works fine, but f13 and above seem to produce the wrong output:

Running xev, the output for F1, F2  is:

f1: (keysym 0xffbe, F1)

f2: (keysym 0xffbf, F2)

...as expected. But for F13, F14:

f13: (keysym 0x1008ff81, XF86Tools)

f14: (keysym 0x1008ff45, XF86Launch5)

However, mapping F13 and F14 in xkb (instead of using kmonad) gives the following, which look correct:

f13: (keysym 0xffca, F13)

f14: (keysym 0xffcb, F14)

**Comment by precondition** [comment]
It's not entirely wrong. The [HID keycode for the F13 key is 0x68](https://gist.github.com/MightyPork/6da26e382a7ad91b5496ee55fdc73db2#file-usb_hid_keys-h-L147), or 104 in decimal. This gets converted by the libinput/evdev driver to keycode 191 (to convert between HID keycodes and keycodes as used by xkb, you can use [this little python script](https://gist.github.com/precondition/cdf18eadc2a9f5600311a17ef58e5f45)) which happens to be mapped by default to XF86Tools.

The F13 *keysym* isn't mapped to any keycode by default, so you can't trigger that keysym using purely KMonad and without touching the OS xkb layout.

**Comment by stevep99** [comment]
Keycode 191 makes sense, if I check in my /usr/share/X11/xkb/keycodes/evdev I see

        <FK13> = 191;

I don't really understand where XF86Tools has come from though. 

What I am trying to do is use F13 and above for custom actions. For example, having F13 in some custom layer in my kmonad config, and then binding F13 to some frequent action within a specific program. The beauty of using F13 to F24 is they tend not to conflict with other bindings/shortcuts, so they would be great for this purpose in theory. Is this a viable use case for kmonad?

**Comment by precondition** [comment]
> I don't really understand where XF86Tools has come from though.

It comes from line 221 of `/usr/share/X11/xkb/symbols/inet`
```
    key <FK13>   {      [ XF86Tools         ]       };
```

If you do `setxkbmap -print` and look at the `xkb_symbols` line, you'll see a mention of `inet(evdev)` at the end. Since you're loading the evdev keysymbols file, that's why XF86Tools gets mapped to the F13 key.

> 

What I am trying to do is use F13 and above for custom actions. For example, having F13 in some custom layer in my kmonad config, and then binding F13 to some frequent action within a specific program. The beauty of using F13 to F24 is they tend not to conflict with other bindings/shortcuts, so they would be great for this purpose... in theory. Is this a viable use case for kmonad?

Sure, you can use KMonad to assign the F13 scancode to one of the keys of your keyboard but if you want a keysym other than XF86Tools when you press it, you'll need to use a xkb layout that changes the mapping of `<FK13>` .

**Comment by stevep99** [comment]
Thanks for the explanation, that helps a lot.

Yes, so it turns out that simply editing the `/usr/share/X11/xkb/symbols/inet` file like this:

        key <FK13>   {      [ F13               ]       };
        key <FK14>   {      [ F14               ]       };

...does exactly what I was trying to achieve. I mean, I don't know why this isn't the default. It almost seems everything in xkb is done in an obtuse and counter-intuitive way.

I'll close this issue as it's not really a kmonad bug.

**Comment by david-janssen** [comment]
Just popping my head in to say that it makes me very happy to see that you've solved your issue, and to compliment @precondition on how well they helped you out :-).
