### ISSUE TITLE
Mac: investigate karabiner 13 and DriverKit

### ISSUE THREAD

**Issue by focusaurus** [david-janssen/kmonad#124]
Karabiner-Elements just [released version 13](https://karabiner-elements.pqrs.org/docs/releasenotes/#karabiner-elements-1300) which moves away from the kernel extension to "DriverKit" based implementation. I have no technical depth in any of these things just repeated the words which I think are relevant but I'd be curious to hear @thoelze1 thoughts on whether kmonad should follow a similar path. Any chance this would allow kmonad to run as a normal user?

**Comment by franco** [comment]
Any news on Big Sur support?

**Comment by thoelze1** [comment]
@franco I'm working on Big Sur support now. I have a kmonad update running on Catalina that should also work on Big Sur. Once I clean things up, I'll make a PR.

@focusaurus To support Big Sur, we have to use the new DriverKit implementation because the kext-based alternative is getting deprecated. Unfortunately, privilege is an issue in both sending and receiving key events to/from macOS. 

Receiving key events requires root however you do it. Currently we receive key events through IOKit. Karabiner uses the same method, so I expect that it too requires root. There is a new DriverKit [method](https://developer.apple.com/documentation/hiddriverkit/handling_keyboard_events_from_a_human_interface_device) but it too requires root privilege. Sending key events requires invoking either a kext or a dext (DriverKit). For the kext, you need root privilege only for initialization. For the dext, you need root privilege for initialization and maybe more (I'm not sure). So I don't think that kmonad on macOS will ever be able to run as a normal user :( I think that privilege separation would be our best bet in terms of limiting privilege requirements, but I don't plan on implementing that.

**Comment by focusaurus** [comment]
@thoelze1 can we make a background service the way karabiner does? Perhaps with a menubar icon control? Whatever karabiner does seems to be reasonable. End user has to click "allow" on a dialog and maybe enable input monitoring in system preferences privacy during initial installation/configuration, but thereafter everything just works OK.

**Comment by thoelze1** [comment]
What exactly do you mean by background service? And are you imagining that this functionality would affect privilege level, or just the user experience?

**Comment by focusaurus** [comment]
Sorry I'm not very familiar with the details of native macos desktop development, but karabiner starts automatically on login and doesn't need `sudo` run from the CLI or a password prompt. I guess I should study their launchd config as that presumably would indicate how it works. Basically all I'm getting it is I can boot up and log in and karabiner is working properly.

**Comment by thoelze1** [comment]
I'm not very familiar with mac desktop development either. But I believe that developing such an application would require a paid Apple Developer ID. So if someone developed a kmonad "app" (with menubar icon control, installation wizard, etc), then they would have to either build, sign, and officially release it themself (this is what Karabiner does), or ask that each user register for (and purchase) an Apple Developer ID to build it.

Anyways, ever since I got launchd working with kmonad, I boot up, log in, and it works. Nobody else has confirmed yet that my method worked for them, but here's the relevant [issue](https://github.com/david-janssen/kmonad/issues/105) in case you want to give it another try
