### ISSUE TITLE
Is it possible to omit input specification and apply the mapping to all inputs

### ISSUE THREAD

**Issue by QiangF** [david-janssen/kmonad#15]
Just to make things simple for lazy people:
1. make 1 configuration work everywhere for standard us english keyboard.
2. make the configuration work at all times for all plugged in keyboard, maybe monitor the input for newly added devices and act if new keyboard is plugged in.

**Comment by QiangF** [comment]
There are two other interesting packages:
https://github.com/snyball/Hawck
https://github.com/kozikow/keyremaplinux

Hawck is more feature rich, keyremaplinux is simple, and there is a blog post on it:
https://kozikow.com/2013/11/15/the-only-alternative-keyboard-layout-youll-ever-need-as-a-programmer/

I am using keyremaplinux for now, it even works in tty, but it messes up my vmware virtual machine.

**Comment by david-janssen** [comment]
This isn't possible yet, but definitely a feature I should support. I'll get on it and let you know how it goes. I'll leave this open until this is resolved.

**Comment by david-janssen** [comment]
Oh, and a quick note: kmonad works in TTY too. Haven't tested it with any virtual machines though.

**Comment by david-janssen** [comment]
So, first of all: thanks for the references to Hawck and Keyremaplinux. They are interesting projects as well, and I might find some inspiration from them in the future.

In regards to your issue: I think just a tiny change makes it possible to support what you want (by combining kmonad with udev-rules). So this is what I did: I simply made it possible to override the keyboard that should be targeted by KMonad using a command-line argument. If you pass the '-i' or '--input' flag, you can then provide a filepath to a `/dev/input` file that KMonad should use instead of the one in the config file.

This allows you to simply write a udev rule that calls KMonad with your one config-file on any keyboard that is plugged in.

It is currently still necessary to have a line describing the input to use in your config file, but I will remove this in the future, so that you can write keyboard-agnostic configs, and just use the command-line to target the input-keyboard(s) of your choice. This might be a while though, since I have some other things I want to take care of first.

If this sufficiently provides for your requirements, feel free to close this issue. Otherwise I will close it myself once I've improved the command-line interface and config-file requirements.

**Comment by QiangF** [comment]
Maybe you should make keyboard-agnostic the default by providing a udev rule working for all keyboards. Udev rules looks very complicated to beginners. Something like this? /etc/udev/rules.d/98-keyboard.rules

    SUBSYSTEM=="input", ENV{ID_INPUT_KEYBOARD}=="1", ACTION=="add", RUN+="/path/to/kmonad -i input/$name path-to-kbd-file"

It is unfathomable to me that we often get better support with free software than paid services. I am in no hurry at all.
By the way, if you use emacs, you should really try https://github.com/ch11ng/exwm 
It's a tiling window manager with floating window support.
Thank you!

**Comment by david-janssen** [comment]
I didn't add the udev rule because I don't know how udev works :D, I just hope others do.

Your suggestion is a good one, and I think I will implement this as a 2nd type of Input Source for Linux, one that installs a udev rule. At the moment I am in the middle of a big refactor to improve some other stuff, but I will let you know when I get to this.

In regards to EXWM, I tried it a while ago, and really liked aspects of it. What was an issue for me then, though, was that the single-threadedness of emacs caused it to freeze quite often, and it wasn't as stable as I liked. I would have to do a hard reset quite often. XMonad is less integrated with emacs, but it is *so unbelievably stable*. I haven't had a crash in months.

**Comment by QiangF** [comment]
I would make three more suggestions:
1. make a inter process communication interface via dbus. So windows manager can use it to set application specific keybindings using kmonad in a window switch hook. For example,
you want a global emacs like C-y to do paste, in some application you need to remap C-y to C-v. In my experience, EXWM's slowness is mostly due to these application specific simulation keys, sometimes it even compete with the application for mapping keys and cause total freezes for freerdp and vmware workstation. By moving the keymapping to a lower lever will also help make window manager like EXWM wayland compatible.
2. make a key binding call an external program, a lot of things can be down with this: like minimise a window, send password etc.
3. make a better default for inexperienced users. From Kozikow's blog post, a good keymap is even for people who is not familiar to your keymap, it will give no t too much surprises, so the good keymap should like this figure:

(1) tab is a layer toggle, when it pressed together with another key, it send the key on the blue layer.
(2) capslock and enter are remapped to ctrl, press with another key they work as a modifier, and press alone will be esc.
(3) leftshift when pressed alone will be backspace.
(4) rightshift when pressed alone will be delete.
![keymap](https://user-images.githubusercontent.com/8192731/67136050-948d3400-f253-11e9-8763-94c7d49e1c02.png)

**Comment by david-janssen** [comment]
Thanks for the suggestions. I already had plans for 1 and 2 in the back of my head, and they are definitely in the works. 3. is a good suggestion as well.

**Comment by david-janssen** [comment]
I've included all of these suggestions in my internal work documents. They aren't done yet, but I'm closing this issue because the core issue was resolved, and the others were interesting ideas that will be worked on in the future. If any of these are currently pressing issues, please file a new issue. This way we can keep issues clean and to the point :-)
