### ISSUE TITLE
fatal error during installation on Mac

### ISSUE THREAD

**Issue by agemartin** [david-janssen/kmonad#185]
I have been trying to install kmonad on OSX Mojave and keep getting the following error (after trying to build build kmonad with stack):

   **fatal error: 'karabiner_virtual_hid_device_methods.hpp' file not found**

screenshot of the terminal message:
https://imgur.com/arkqVZj

Not sure if it was a proper thing to open an issue, just can't google anything to that. 

Big up to David Janssen and the whole team for this project, sort of dream coming true really!

**Comment by thoelze1** [comment]
Did you clone the repo recursively? We use Karabiner as a submodule, so it has to be pulled as well. The docs might not be clear on this, I'll have a look later. Please let me know how it goes

**Comment by agemartin** [comment]
I have used the commands from the installation guide,
` git clone --recursive https://github.com/david-janssen/kmonad.git`

I have been using Karabiner already, so I guess that should not be the problem?

Thanks a lot for the immediate reply!

**Comment by thoelze1** [comment]
I've been traveling but I just got a chance to look at this again. It looks like the issue is that we're not telling cabal where to look for this included file (which is weird, because I think we were in the past). I may have changed something by mistake. I will look into it and comment again shortly.

**Comment by thoelze1** [comment]
Aha, figured it out (I think). On Mac, you need to pass `stack` the location of the `Karabiner` include directory. The documentation provides the following command to do that:

```shell
stack build --extra-include-dirs=c_src/mac/Karabiner-VirtualHIDDevice/dist/include
```

It looks like you were running this command from your home directory, one directory up from where the documentation expected you'd be. To fix this, you can run `cd kmonad` and then execute the above command, or you could just execute:

```shell
stack build --extra-include-dirs=kmonad/c_src/mac/Karabiner-VirtualHIDDevice/dist/include
```

from your home directory. Or run `stack` from whatever directory you want, as long as you pass the corresponding relative path (or just the absolute path) of the include dir.

Ideally you wouldn't have to manually specify the include directories. We used to tell `stack` where to locate included files by specifying directories in `kmonad.cabal`. But this interfered with deploying `kmonad` to `hackage` (because `Karabiner` is a submodule and `hackage` didn't like that or something). So now you have to specify the include dirs as a command line argument. If you want, see [this small commit](https://github.com/david-janssen/kmonad/commit/896c687283eb07fae66a8400011cfe74f1e9e1c0) for the change and [this issue](https://github.com/david-janssen/kmonad/issues/75) about `hackage`.

**Comment by agemartin** [comment]
great, that worked (just did executed straight the following):
`stack build --extra-include-dirs=kmonad/c_src/mac/Karabiner-VirtualHIDDevice/dist/include`

seems the building process finished succesfully. Thank you!!

OFF TOPIC:
Just don't really understand how the rest is supposed to work. I understand I have to edit /create a keymap/configuration file - and than (I guess) I have to tell the system to read it. There is a "user" folder in the "keymap" folder. I guess I am supposed to have mine there? but how do I tell the system to process it / accept it? 

I have hardly any experience with stuff like that, super happy to learn that and I am not expecting this to be straigt forward or easy, just to me it seems like this is missing in the documentation? or I just can't see it? 

I guess the issues here is not the place for such questions?

**Comment by thoelze1** [comment]
I think it's fine if you ask here. Others may have the same questions, and this little corner of `kmonad` probably won't see much traffic anyways. I'll explain further below, feel free to ask about anything you don't understand

What you can do next is run the executable that you built (at the end of the build process, `stack` prints the location where it put the executable). I don't know much about stack, but for me it was a long cumbersome path to the executable:

```
~/git/kmonad/.stack-work/install/x86_64-osx/30d9f5448a20d1378752862cae4f5c7028a65768b7be33d29d49b56f2ff59bcf/8.6.5/bin/kmonad
```

This is difficult to type and work with so I just made a symbolic link from a directory in my `$PATH`:

```
$ ln -s kmonad/.stack-work/install/x86_64-osx/30d9f5448a20d1378752862cae4f5c7028a65768b7be33d29d49b56f2ff59bcf/8.6.5/bin/kmonad /usr/local/bin/kmonad
```

I suppose you could probably tell `stack` where to place the `kmonad` executable (probably via a command line argument) so that you don't have to deal with such a long path even in your symbolic link.

Anyways, you can then simply run `kmonad` without arguments and it will print some useful info about how to use it properly:

```
$ ./kmonad
```

if you've symlinked it, or something like

```
$ kmonad/.stack-work/install/x86_64-osx/30d9f5448a20d1378752862cae4f5c7028a65768b7be33d29d49b56f2ff59bcf/8.6.5/bin/kmonad
```

to just run it from wherever `stack` dropped it.

You can then just copy the default config (put it wherever you'd like, doesn't have to be in `keymap/user` or anything), then just pass `kmonad` the path of wherever you put it. I keep my config in a git repo with all of the configuration files I use for other software

**Comment by agemartin** [comment]
thanks for the answers!

I have lost the path at first (just closed the terminal after the building process was finished), so tried to ask "stack" what it can do, tried `stack run` which just started the building process again, at the end of which I got the path to the bin folder, so I just added. `/kmonad` at the end of the path and run that ,... and yeah! now it seems to be communicating with me. So I just put a copy of the default config anywhere and ... this is the question now: how do I pass `kmonad `the address? 

I tried `file --help` but not really getting it what I should do

really appreciate the help.

**Comment by thoelze1** [comment]
> how do I pass kmonad the address?

You pass it as a command line parameter. When you run kmonad as

```
$ ~/path/to/kmonad
```

Then you will get the following output:

```
kmonad - an onion of buttons.

Usage: kmonad FILE [-d|--dry-run] [-l|--log-level Log level]
  Start KMonad

Available options:
  FILE                     The configuration file
  -d,--dry-run             If used, do not start KMonad, only try parsing the
                           config file
  -l,--log-level Log level How much info to print out (debug, info, warn, error)
  -h,--help                Show this help text
```

The second line says `Usage: kmonad FILE...` which means that `kmonad` expects a configuration file as its first parameter. So if you save your config as `~/kmonad_config.kbd`, then you will run

```
$ kmonad ~/kmonad_config.kbd
```

Or, in general, you're going to execute

```
$ ~/path/to/kmonad ~/path/to/config.kbd
```

> also - by "the default config file" you mean tutorial.kbd, right?

Yes

**Comment by agemartin** [comment]
this is really helpful, understanding it more and more. thank you very much. will continue with this tomorrow or during the weekend.

**Comment by thoelze1** [comment]
Happy to hear it. Let me know if you run into more trouble.

**Comment by desmap** [comment]
> We use Karabiner as a submodule

@thoelze1 out of curiosity, why? Is kmonad just a higher-level api to karabiner or do you use just some low-level kext thing from karabiner?

**Comment by desmap** [comment]
Ok, I think I found it myself, this here right? https://github.com/david-janssen/kmonad/issues/67#issuecomment-688552251

**Comment by thoelze1** [comment]
> We use Karabiner as a submodule

I meant to say that we use [Karabiner-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-VirtualHIDDevice) as a submodule (as opposed to [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements)). Karabiner-VirtualHIDDevice provides a kext that you can think of as an API that both kmonad and Karabiner-Elements use (though both the kext and Karabiner-Elements are developed by the same person).

kmonad needs a way of posting modified key events back to the macOS, so we use the kext for this. There are alternative event posting methods, which are discussed [here](https://github.com/pqrs-org/Karabiner-Elements/blob/master/docs/DEVELOPMENT.md). I tried the other methods out on two branches [here](https://github.com/thoelze1/kmonad/tree/cgeventpost) and [here](https://github.com/thoelze1/kmonad/tree/iohidpostevent) but they were undesirable for one reason or another.

**Comment by desmap** [comment]
The repo you linked is archived. Did you mean this one based on DriverKit which also supports Big Sur: https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice

If not, is it technically possible to migrate to the DriverKit one?

**Comment by MuhammedZakir** [comment]
> The repo you linked is archived. Did you mean this one based on DriverKit which also supports Big Sur: https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice
> 
> If not, is it technically possible to migrate to the DriverKit one?

KMonad currently uses kext (archived one). @thoelze1 is working on adding support for DriverKit implementation. See https://github.com/david-janssen/kmonad/issues/124#issuecomment-782614661.

---

> I suppose you could probably tell stack where to place the kmonad executable (probably via a command line argument) so that you don't have to deal with such a long path even in your symbolic link.

You can use `stack install`, which is shortcut for `stack build --copy-bins`, which will copy binaries to `local-bin-path` (see `stack path`). Default `local-bin` dir is `~/.local/bin`.

**Comment by agemartin** [comment]
> > how do I pass kmonad the address?
> 
> You pass it as a command line parameter. When you run kmonad as
> 
> ```
> $ ~/path/to/kmonad
> ```
> 
> Then you will get the following output:
> 
> ```
> kmonad - an onion of buttons.
> 
> Usage: kmonad FILE [-d|--dry-run] [-l|--log-level Log level]
>   Start KMonad
> 
> Available options:
>   FILE                     The configuration file
>   -d,--dry-run             If used, do not start KMonad, only try parsing the
>                            config file
>   -l,--log-level Log level How much info to print out (debug, info, warn, error)
>   -h,--help                Show this help text
> ```
> 
> The second line says `Usage: kmonad FILE...` which means that `kmonad` expects a configuration file as its first parameter. So if you save your config as `~/kmonad_config.kbd`, then you will run
> 
> ```
> $ kmonad ~/kmonad_config.kbd
> ```
> 
> Or, in general, you're going to execute
> 
> ```
> $ ~/path/to/kmonad ~/path/to/config.kbd
> ```
> 
> > also - by "the default config file" you mean tutorial.kbd, right?
> 
> Yes
> 
> Edit: Also, you have to run `kmonad` with `sudo` on Mac

I am sorry for the laty reply here. I have been occupied with other stuff lately and just did not want to dig into this, seeing all the hours tweeking the keymap in front of me xD. 

Just tried to set it up now and got error saying 
`kmonad: Not available under this OS: DeviceSource
`

I am on Mojave 10.14.6 (18G8022) so compatibility should not be an issue, no?

**Comment by thoelze1** [comment]
Have you commented out the linux-specific portions of the `defcfg` block (and uncommented the mac-specific portions) as tutorial.kbd describes?

**Comment by agemartin** [comment]
> Have you commented out the linux-specific portions of the `defcfg` block (and uncommented the mac-specific portions) as tutorial.kbd describes?

Yep that was it! Thx a lot.

Now just having hard time trying to realize how to emit č ě š ť... the czech special characters. seems like á é í ó ú ý should work easily since the ´ dead key is usual for french etc so I can just trigger a macro. But for ˇ I have not found a solution yet. And have not really tried for ů yet.

I think I will write a tutorial for those rather illiterate like myself. 😇 

Thanks all for all the help!!

**Comment by agemartin** [comment]
>> Now just having hard time trying to realize how to emit č ě š ť... the czech special characters. seems like á é í ó ú ý should work easily since the ´ dead key is usual for french etc so I can just trigger a macro. But for ˇ I have not found a solution yet. And have not really tried for ů yet.
> 

I found out also through reading the older closed issues, will just have to built the whole keymap based on the czech layout (i.e. having czech layout active when using kmonad rather then - as kmonad would expect - english layout). In this specific case because ther is no dead key for ˇ on the english keyboard (or I have not found it)...

This comes with some work defining all symbols (including the more common ones as %) as combinations of keys on the czech layout. But once done, it should allow me to write anything I need. 

Thank you so much for the support. Any way to buy you a coffee or something?

**Comment by molleweide** [comment]
> Big up to David Janssen and the whole team for this project, sort of dream coming true really!
+1!!!

**Comment by molleweide** [comment]
> $ ~/path/to/kmonad ~/path/to/config.kbd

this is nice! I know this is what happens under the hood with unix paths n stuff but I have never written it out like this and it changes my perspective a lot. it is a bit mind blowing for me.
