### ISSUE TITLE
Contributing on develop vs on master?

### ISSUE THREAD

**Issue by thoelze1** [david-janssen/kmonad#189]
[CONTRIBUTING.md](https://github.com/david-janssen/kmonad/blob/master/CONTRIBUTING.md) says

> - Pull requests for new features should be made against the develop branch.
> - Pull requests for improvements to the documentation, as well as bug fixes, of existing features should be made against the master branch.)

I'm testing a new feature so I made a branch off of `develop` and committed some new changes. I then realized that `develop` lacks some bug fixes present on `master` and that they're interfering with my changes. What is the proper way to address this? Should I have made a branch off of `master` and then PR'd against `develop`?

**Comment by david-janssen** [comment]
Hey Tanner,

I actually don't really know this myself yet. I looked into the discrepancies and merging develop and master, but the issue lies in the keycode representations. My idea was to fix keycodes first (in its own branch), then merge that into develop, and then merge all the changes from master into develop, then bugfix develop until it is good, and then merge everything back in master so master is up to date with develop.

I think the best thing to do would be to prevent stuff like this from happening in the future, but I don't really know what the best way to approach this is. Any advice/ideas? Particular rules or best-practices we should try to enforce?

**Comment by thoelze1** [comment]
I have an update that supports the latest version of macOS. Once we decide how to proceed, I'll make some commits

**Comment by david-janssen** [comment]
We (you!) solved this issue in #229! Wahay!
