### ISSUE TITLE
Compose not working

### ISSUE THREAD

**Issue by AckslD** [david-janssen/kmonad#194]
I have compose as right alt, i.e.
```
setxkbmap -option compose:ralt
```
and set it also in kmonad config
```
cmp-seq RightAlt
```
but I cannot compose e.g. umlauts by pressing
```
ralt shift+'(") a
````

I also tried in kmonad to use `cmp-seq ralt` instead but also does not work.

**Comment by stevep99** [comment]
Don't know if OP still has this issue, but just going to chime in with a suggestion, as I also couldn't get compose to work initially but actually it does work when configured correctly.

Depending on the OS, you may it looses any previously set options using setxkbmap upon running kmonad. I get this on Ubuntu (for example) because it seems to reset keyboard config when it detects a change to the USB device. Presumably this happens because Kmonad is adds an extra output USB device. Consequently, setting "setxkbmap -option compose:ralt" before running kmonad is ineffective.

The solution I found was to set compose key at the OS-level way, in my case using Gnome Tweaks. Then, when there is a change to the USB device, it will reset xkb settings inline with what's set there, and the compose option will work.

**Comment by AckslD** [comment]
Thanks @stevep99! I never got it working and instead added a mapping to switch keyboard layouts (to type öäå).

If what you mention is needed then I'm not sure what the option `cmp-seq` is meant to do. I thought the intention was to handle this so that one wouldn't have to manually set it as well.

**Comment by stevep99** [comment]
You would still need `cmp-seq` in your kmonad configuration I beleive, and you should set it to the same key that's defined in the OS. This is so that kmonad and the OS have the same understanding what the compose key is set to.

**Comment by slotThe** [comment]
> If what you mention is needed then I'm not sure what the option `cmp-seq` is meant to do. I thought the intention was to handle this so that one wouldn't have to manually set it as well.

The point is that we enter unicode via the X11 compose-key sequences and thus we need to know which key the X server expects to see as the compose key.  You can specify this in the `defcfg` to have all of it in one place:

``` clojure
(defcfg
  input (device-file "...")
  output (uinput-sink
          "Keyboard-Name"
          "sleep 0.2s; setxkbmap -option compose:menu")
  cmp-seq compose)
```

I will close this as solved for now; though feel free to chime in if there's something that's still bothering you!
