### ISSUE TITLE
super+some keys not work propetly

### ISSUE THREAD

**Issue by n1rdeks** [david-janssen/kmonad#205]
Hello, guys.
I use DWM with dvorak-programmer keymap.
In this WM  for changing layout i use mod4+'&' or '[' or '{' etc.
``` 
part of config.h (DWM)
        TAGKEYS(               XK_ampersand,                     0)
        TAGKEYS(               XK_bracketleft,                      1)
        TAGKEYS(               XK_braceleft,                         2)
        TAGKEYS(               XK_braceright,                       3)
        TAGKEYS(               XK_parenleft,                         4)
        TAGKEYS(               XK_equal,                              5)
```
With using kmonad + configfile  (attached) mod4 switched only with "bracketleft" and "equal". All other symbols not work. 

My configfile attached (just rename .txt to .kbd)
[dvp.txt](https://github.com/david-janssen/kmonad/files/6217483/dvp.txt)

**Comment by MaxGyver83** [comment]
What is your xkb layout (`setxkbmap -query`)?

**Comment by MaxGyver83** [comment]
IIRC, I had similar problems (in DWM). But I don't remember how I fixed them. It might be necessary to start KMonad before dwm.

**Comment by n1rdeks** [comment]
```
setxkbmap -query
rules:      evdev
model:      pc105
layout:     us
```

my config in .xinitrc (and Sway,River,DWL too)
```
setxkbmap -option ctrl:nocaps -option grp:win_space_toggle us,ru -variant dvp,typewriter
```
>I had similar problems (in DWM)

I didn't have any problem with DWM or Xmonad ;)
This is only keys with Meta4: "&", "{", "}", "(" maybe more... But meta+[ work, meta+= work too...
If i recompile to another, for example, comma, semicolon, period - all work fine.
Maybe i writed wrong config? Or maybe, IMHO, this is bug?

P.S. Sorry for my English.

**Comment by MaxGyver83** [comment]
`[` and `=` have in common that they are in the first level in a US keyboard layout. When you type `{` in your dvorak-programmer layout, KMonad will translate this to `Shift-[`. And that's what DWM sees. For other dwm keybinding, you could just write `Mod4Mask|ShiftMask, XK_braceleft, ...` instead of `Mod4Mask, XK_braceleft, ...`. But for the `TAGKEYS` macro it's not that easy because it defines keybindings with and without `Shift`. I don't know how to deal with this right now.

**Comment by n1rdeks** [comment]
Thanks! Amazing answer!

Where l look at this translates? And why? Why KMonad don't use standard keycode? 
If people for any reasons use this keys for another shortcuts? Or this situation only with Logo/Super/Mod4Mask key?

How fix this translation? 

P.S. Today i changed hotkeys in DWM in second row, work good.

**Comment by MaxGyver83** [comment]
You can use `xev -event keyboard`. When you type `{` you should get an output like this:

```
KeyPress event, serial 28, synthetic NO, window 0x2800001,
    root 0x7c9, subw 0x0, time 28997684, (2127,1129), root:(2140,1167),
    state 0x10, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x2800001,
    root 0x7c9, subw 0x0, time 28997685, (2127,1129), root:(2140,1167),
    state 0x11, keycode 34 (keysym 0x7b, braceleft), same_screen YES,
    XLookupString gives 1 bytes: (7b) "{"
    XmbLookupString gives 1 bytes: (7b) "{"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2800001,
    root 0x7c9, subw 0x0, time 28997686, (2127,1129), root:(2140,1167),
    state 0x11, keycode 34 (keysym 0x7b, braceleft), same_screen YES,
    XLookupString gives 1 bytes: (7b) "{"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x2800001,
    root 0x7c9, subw 0x0, time 28997686, (2127,1129), root:(2140,1167),
    state 0x11, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by n1rdeks** [comment]
without KMonad

```

KeyRelease event, serial 29, synthetic NO, window 0x2400001,
    root 0x1a3, subw 0x0, time 5713959, (333,770), root:(333,770),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2400001,
    root 0x1a3, subw 0x0, time 5714863, (333,770), root:(333,770),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2400001,
    root 0x1a3, subw 0x0, time 5716215, (333,770), root:(333,770),
    state 0x40, keycode 12 (keysym 0x7b, braceleft), same_screen YES,
    XLookupString gives 1 bytes: (7b) "{"
    XmbLookupString gives 1 bytes: (7b) "{"
    XFilterEvent returns: False
```

with Kmonad and my file (attached)

```
xev -event keyboard
Outer window is 0x1c00001, inner window is 0x1c00002

KeymapNotify event, serial 24, synthetic NO, window 0x0,
    keys:  0   0   0   0   16  0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 24, synthetic NO, window 0x0,
    keys:  0   0   0   0   16  0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyRelease event, serial 25, synthetic NO, window 0x1c00001,
    root 0x1a3, subw 0x0, time 5542031, (644,698), root:(644,698),
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
"   XLookupString gives 1 bytes: (0d) "
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x1c00001,
    root 0x1a3, subw 0x0, time 5543399, (644,698), root:(644,698),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x1c00001,
    root 0x1a3, subw 0x0, time 5543591, (644,698), root:(644,698),
    state 0x40, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x1c00001,
    root 0x1a3, subw 0x0, time 5543591, (644,698), root:(644,698),
    state 0x41, keycode 34 (keysym 0x7b, braceleft), same_screen YES,
    XLookupString gives 1 bytes: (7b) "{"
    XmbLookupString gives 1 bytes: (7b) "{"
    XFilterEvent returns: False
```

You are right. So?..
[dvp.txt](https://github.com/david-janssen/kmonad/files/6217721/dvp.txt)

**Comment by MaxGyver83** [comment]
OK, apparently XKB remaps the keyboard in a way that it can send a `{` without sending `shift` first. I don't know if this could be achieved with KMonad. Maybe not because it's not a running close enough to the system. @david-janssen , @slotThe : Why does KMonad send key combinations like someone would do on a US keyboard? Would it be possible to send just a `{` key (like with `setxkbmap us -variant dvp`)?

**Comment by n1rdeks** [comment]
Well, I'm a noob in Haskell, but if u give in sum function some, for example 2 and 3, you always, ALWAYS receive five. Pure, bla-bla. 
Respect for the good choice of technology for this project. 

I think, maybe I'm wrong, this is bug/misprint in keycode map or array or DB, whatever. Or somebody hardcoded in KMonad for symbols `{` `&` `}` `(`  code with combinations, because in US QWERTY this symbols available only with `Shift`:
Watch this picture: https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/KB_United_States.svg/400px-KB_United_States.svg.png

**Comment by MaxGyver83** [comment]
You don't have to create a layout based on the US layout. [My KMonad layout](https://github.com/MaxGyver83/dotfiles/blob/master/kmonad/.config/kmonad/vou-linux-de-rctrl.kbd), for example, is based on German QWERTZ (because of some open issues).

So you could base your KMonad layout on XKB's `us`/`dvp` (see below). Then you could send a simple `{` without `Shift`. But this is not perfect either because with this config KMonad will have to send a `Shift` for every number on your extended layer.

```clojure
(defcfg
  ;; input  (device-file "/dev/input/by-id/usb-Topre_Corporation_HHKB_Professional-event-kbd")
  input  (device-file "/dev/input/event22")
  output (uinput-sink "KMonad output"
    "/bin/sleep 1 && setxkbmap us -variant dvp")
  fallthrough true
)

(defsrc
  esc    1    2    3    4    5    6    7    8    9    0    -    =    \    `
  tab     q    w    e    r    t    y    u    i    o    p    [    ]  bspc
  lctl     a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft      z    x    c    v    b    n    m    ,    .    /    rsft
           lmet lalt            spc          ralt rmet
)

(defalias  ext  (layer-toggle extend))

(deflayer dvorak-programmer
  esc     _    _    _   _    _    _    _   _    _    _    _    _    _    _
  tab      _    _    _    _    _    _    _    _    _    _    _    _    bspc
  lctl      _    _    _    _    _    _    _    _    _    _    _    ret
  lsft       _    _    _    _    _    _    _    _    _    _    rsft
            lmet lalt           spc            @ext rmet
)

(deflayer extend
   _       f1   f2   f3   f4  f5   f6   f7   f8   f9   f10  f11  f12   _    _
   _        _    S-2  S-min S-6    _    _    _    up   _    _    _    _    _
   _         _    S-9  S-3  S-0    _    _    left down rght    _    _    _
   _          _    S-5  S-8  S-4    _    _    _    _    _    _    _
            _    _             _              _    _
)
```

**Comment by slotThe** [comment]
On Sun, Mar 28 2021 14:09, Max Schillinger wrote:
> @david-janssen , @slotThe : Why does KMonad send key combinations like
> someone would do on a US keyboard? Would it be possible to send just a
> `{` key (like with `setxkbmap us -variant dvp`)?

We can only really send `Keycode`s as defined in
`KMonad.Keyboard.Keycode` and, while there are keys for parentheses and
brackets, there simply isn't one for curly braces.

I'm not sure how one would go about sending `{` as a single entity; I'll
try to look into how other programs are doing that.

**Comment by david-janssen** [comment]
> I don't know if this could be achieved with KMonad.

Actually, as I understand, you simply cannot send a single `}` in pure-Linux, because there is no keycode for it. X11 has keycodes for that, but we don't support X11 because the OSes don't agree on a way to have unicode characters, they all have different insertion mechanisms that we'd have to keep track of. All OSes respect that `shift-]` should become `}` in the 'default' setting, so that is what we emit. 

Maybe down the line we can support different OS-translations, or maybe the OSes all agree on a simple way to represent UTF-8 typing, but until that time comes, we benefit from keeping the core of our data simple and focusing our efforts on interesting transformations instead.

I think I'm gonna close this, because there is nothing to address, but we should at some point address this issue in a very central way in our documentation, because it keeps cropping up.
