### ISSUE TITLE
Emitting multiple modifier keys

### ISSUE THREAD

**Issue by mwgkgk** [david-janssen/kmonad#21]
Like this:
```
@a1 = C-M-S-lalt
```
The usecase being, using this in combination with other keys, to trigger actions from the hotkey manager. This example uses 4 modifiers, but 3 or 2 exhibit same behavior: `KeyPress` and `KeyRelease` are all emitted together on `@a1` keypress, so it's not possible to combine it with other keys.

Related question: what is the best strategy for sending unique key combinations for the hotkey manager to consume? F13-F24 doesn't seem to work on my machine (F13 seems to send the keycode for F21, and sxhkd is not catching either). Currently using super-key combos that I do not use, e.g. M-6, M-7; The drawback being that these are limited and have side-effects, such as Super being registered as pressed, or a Vimperator prompt closing prematurely when this is emitted.

Edit: disregard the Vimperator prompt bit, the reason behind this is that I've moved on from using XkbOptions for layout switching on `grp:lctrl_rctrl_switch`, to firing M-6 and M-7 on the same physical keys, triggering a switch manually using [xkb-switch](https://github.com/ierton/xkb-switch). The difference probably being that xorg.conf.d has a special way of handling keys that Vimperator is oblivious to.

**Comment by david-janssen** [comment]
Heh, that's weird. Something like:
```
@a1 = C-M-S-lalt
```
should simply work.

I will investigate and get back to you.

Additionally, that also seems like an answer for your second question. I tend to go for crazily unique combinations that no sane program would ever use like: S-C-M-A-F1

Also, I am a bit surprised by the F13 being mapped to F21 and such. Are you on some non-US keyboard layout? Do you have other key-remapping stuff setup (like xmodmap). What is the output of `evtest` when you press those keys? I haven't personally used any F>12 key, but looking at the code there should be no reason for these to behave strangely.

Anyways, will investigate your first issue and get back to you in a bit.

**Comment by mwgkgk** [comment]
Thank you for pointing out `evtest`. It reports the correct events for f13 and such. For reference, here's the output from `xev` that confused me:
```
KeyPress event, serial 32, synthetic NO, window 0x2a00001,
    root 0xf7, subw 0x0, time 950496, (597,123), root:(598,138),
    state 0x0, keycode 191 (keysym 0x1008ff81, XF86Tools), same_screen YES,
    XKeysymToKeycode returns keycode: 179
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2a00001,
    root 0xf7, subw 0x0, time 950584, (597,123), root:(598,138),
    state 0x0, keycode 191 (keysym 0x1008ff81, XF86Tools), same_screen YES,
    XKeysymToKeycode returns keycode: 179
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```
Not sure which one of 191 and 179 is the correct one, but `evtest` correctly reports 183, for f13. Neither sxhkd nor dwm are able to catch them however.

I do suspect there's something non-us about my keyboard or layout, because the `dot` key needs to be referred as `period` for the mapping to work in sxhkd. Otherwise it's narrow-enter, `XkbLayout` is `us`, and `$LANG` is `en_US.UTF-8`, both of which are probably irrelevant for this though. `.Xmodmap` is currently empty.

**Comment by david-janssen** [comment]
Hmmmm, so I had a quick look at `sxhkd` since I don't use it myself. It seems it maps X-keyboard events to user-defined actions, right? This means the issue might be in the mapping between Linux key events at the `/dev/input` level and X-key events. `kmonad` remaps `/dev/input` level key-events to other `/dev/input` level key events. Then X comes along and interprets those as X-input events. 

So, I had a quick look at your first issue as well, and you are *completely* right. The `C-M-S-lalt` syntax defines a button that *taps* `lalt` in the presence of `C-M-S`, but doesn't hold on press, and release on release. There is no reason it should be this way, so this is something I should fix.

In the meantime, you could just define a different `C-M-S-A-x` button for any complicated button you want to tap. It makes more sense to specify 1 multi-mod button, and I will let you know when I've fixed things so this works. When I've fixed this, I'll close this issue. (It might me a bit, I'm working on something else at the moment, but I've put it on the list :-))

**Comment by mwgkgk** [comment]
Thank you :)

For reference, the solution for F13+ keys is to use the keysym from the `xev` output, just like sxhkd suggests. In the above chunk of code it's `XF86Tools`. F13-F24 all correspond to events like this (e.g. `XF86TouchpadOn`, `XF86Launch6`, etc). F19 and F24 however both produce `NoSymbol` with code `0x0`.

**Comment by david-janssen** [comment]
Yeah, I guess that is how X maps your F13-24 keys to its own internal keys. Using the `xev` output is the right idea.

**Comment by david-janssen** [comment]
This was solved a while ago but I forgot to close. Closing now.
