### ISSUE TITLE
Rolling and holding keys in a given layer outputs sigils according to qwerty layout's shift level, not the layer

### ISSUE THREAD

**Issue by mklcp** [david-janssen/kmonad#217]
Take the following config

````

(defcfg
  ;; ** For Linux **
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")

  output (uinput-sink "")

  fallthrough true
)

(defsrc
	q s spc
)


(deflayer base
	q s (layer-toggle sym)
)

(deflayer sym
	/ ~ (layer-toggle sym)
)
````

So the space key is a modifier for a symbol level.
The sequence `Pspc Ps Rs Pq Rq` correctly produces `~/`.
However, `Pspc Ps Pq Rs Rq`*incorrectly* produces `~?`.
`?` is output (instead of `/`) because on qwerty, `shift+/` is `?`
I've tested that with other symbols. When holding a key too long in a layer., the followings are computed according to Qwerty, not the layer.

**Comment by mklcp** [comment]
Well, that's not a bug, that's a feature! @slotThe 

As you said in another thread:

> Emitting the correct keycodes allows us to be agnostic of the environment for most things (i.e. we don't care if the user is running X11 or wayland or a TTY).

Here, `~` is output because its keycode is sent, not a symbol.
And because `~` is on the shift level of the qwerty keyboard, holding it down implicitly presses the shift key.
So hence the wrong behaviour: `?` is emit instead of `/` because shift+/ is ? on qwerty..

It would be cool that kmonad offers the possibility to emit symbols directly, whether by generating a custom locale (see #111) or by emitting symbols like `~` (and even normal letters, because this affects them too) as Compose bindings

**Comment by david-janssen** [comment]
> It would be cool that kmonad offers the possibility to emit symbols directly, whether by generating a custom locale (see #111) or by emitting symbols like ~ (and even normal letters, because this affects them too) as Compose bindings

Maybe someday, but anything X11 specific sounds like a huge headache to make cross-platform. Although I think having *customizable* compose sequences would be cool (actually, this is already possible, compose sequences are just syntactic sugar would key macros, so you could just define all the keymacros by hand. Oh my, what fun :p)

Thinking about it, there was a reason we did this. The reason is this:
If we encode a `?` output as:
- When you press me, press shift then /
- When you release me, release / then shift
Then you can press this `?` button and get a stream of `?`, which seems to be the most important behavior to support.

I'm going to close this for now, because any solution I can think of seems like a bigger problem than the current solution. If you have ideas, however, feel free to tell me and I will reopen.
