### ISSUE TITLE
ret, bspc, and spc obliterated upon start

### ISSUE THREAD

**Issue by bryce-carson** [david-janssen/kmonad#221]
Sometimes when the systemd service is started, or when kmonad is used from the command-line, the return key does nothing and I will need to use kprt. Othertimes, bspc and spc suffer the same.

When I start the systemd service from my terminal as root, or as a regular user, sometimes upon hitting the return key it is emitted a bunch of times, causing the shell to throw up a bunch of prompts until I hit an arrow key. That is usually the case when ret is unavailable on my system afterwards. Sometimes not.

When I start kmonad (not as service) from my terminal I get the same behaviour as above.

To avoid this, I am trying `sleep 1; systemctl start kmonad; sleep 1` ⏎. It seems to have worked this time, but I'm not sure if it will work on boot or whatnot. I have enabled `--log level info` in the service unit, and hopefully that will help things.

```lisp
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-id/usb-Microsoft_Natural®_Ergonomic_Keyboard_4000-event-kbd")
  output (uinput-sink "MicrosoftErgonomicEmacs"
                       ;; To understand the importance of the following line, see the section on
                       ;; Compose-key sequences at the near-bottom of this file.
                       "sleep 1 && setxkbmap")
  ;; cmp-seq ralt  ;; Set the compose key to `RightAlt'

  ;; Comment this is you want unhandled events not to be emitted
  fallthrough true

  ;; Set this to false to disable any command-execution in KMonad
  allow-cmd false
)

(defsrc
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12        ssrq slck pause
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc  ins  home pgup  nlck kp/  kp*  kp-
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \     del  end  pgdn  kp7  kp8  kp9  kp+
  caps a    s    d    f    g    h    j    k    l    f    '    ret                        kp4  kp5  kp6
  lsft z    x    c    v    b    n    m    ,    .    /    rsft                 up         kp1  kp2  kp3  kprt
  lctl lmet lalt           spc            ralt rmet cmp  rctl            left down rght  kp0  kp.
)

;; The only thing that is different is the position of Control, Meta, and Super.
(deflayer Emacs
  caps  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12        ssrq slck pause
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc  ins  home pgup  nlck kp/  kp*  kp-
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \     del  end  pgdn  kp7  kp8  kp9  kp+
  esc a    s    d    f    g    h    j    k    l    f    '    ret                        kp4  kp5  kp6
  lsft z    x    c    v    b    n    m    ,    .    /    rsft                 up         kp1  kp2  kp3  kprt
  lmet lalt lctl           spc            rctl lalt lalt  rmet            left down rght  kp0  kp.
  )

```

**Comment by david-janssen** [comment]
Basically, when KMonad is started, there is no way for us to 'do' anything with the source-keyboard that you are trying to remap. So you have to make sure you aren't pressing any keys when kmonad launches.

I've added a configurable startup delay (#233) (defaulting to 300ms) between KMonad starting up, and us grabbing the keyboard you wish to remap. This seems to be plenty for me, in normal typing, to start kmonad from the terminal without anything going on (I have to be extra-quick around 100ms or so).

If you are getting other keys obliterated, are you sure those keys are not being pressed when KMonad starts up?  I'm going to close this for now, because I think we've identified your issue and fixed it, but if this is still a problem, please let me know and we can dig deeper.
