### ISSUE TITLE
Execute command on layer change

### ISSUE THREAD

**Issue by slotThe** [david-janssen/kmonad#25]
Sometimes it might be desirable to execute a shell command whenever the layer changes (e.g. if you wanted to change the input language of your keyboard on layer X).  I don't think this is possible right now.

I would try hacking this in myself but I'm not sure how extensive the planned refactoring will be.  I'd rather wait until it's (mostly) finished before trying to add new features (though I just realized that there is another branch for that and you haven't been doing all the development offline :o).

**Comment by scottrosenquist** [comment]
Another use case I can think of, is updating some UI, either a status icon, or maybe a notification, indicating the layer state to the user. I don't know if I'd personally use that, but it might be interesting.

**Comment by david-janssen** [comment]
Hey guys,

Thanks for the feedback. What you describe is definitely useful, and very much in the planning. Let me tell you very quickly what I strove to achieve in the refactor: instead of having a number of predefined buttons I defined a number of basic 'action' primitives (things like 'emit event', 'wait for condition', 'pause for n milliseconds', and ways to compose and sequence these actions). Then I rewrote the most important buttons in this action DSL. The idea being that I can expose this mini-language to the user, so that people could define their own buttons (like writing a tap-mod, multi-tap, or other, weird combinations). I basically got the entire engine up and running, and now I need to redo the specification language and some smaller functionalities (like launching an external script and redoing the special-symbol stuff).

However, I have really bad allergies, and since the beginning of about this month I've been really quite sick. Same thing happened last year and it passed again somewhere in February. At the moment I am stuck inside and getting very little done, so I hope you can maintain your patience. The project is very much not abandoned, and I think you will really like the refactor when it releases.

Again, thanks so much for being excited about this project, it is very heartening to know people follow and appreciate this work.

**Comment by wismill** [comment]
@david-janssen thank you for all your work. I wish you a quick recovery. Take care

**Comment by david-janssen** [comment]
Thanks :-)

I'm used to it, it comes and goes, and the best thing to do when it comes is to try and not mind it too much.

**Comment by slotThe** [comment]
> Let me tell you very quickly what I strove to achieve in the refactor: instead of having a number of predefined buttons I defined a number of basic 'action' primitives (things like 'emit event', 'wait for condition', 'pause for n milliseconds', and ways to compose and sequence these actions). Then I rewrote the most important buttons in this action DSL. The idea being that I can expose this mini-language to the user, so that people could define their own buttons (like writing a tap-mod, multi-tap, or other, weird combinations). I basically got the entire engine up and running, and now I need to redo the specification language and some smaller functionalities (like launching an external script and redoing the special-symbol stuff).

That sounds absolutely delightful, thank you so much for that overview!  I'm a bit busy these next few weeks, but after that I'm very excited to start properly contributing to this, should you need help with anything.

> However, I have really bad allergies, and since the beginning of about this month I've been really quite sick. Same thing happened last year and it passed again somewhere in February. At the moment I am stuck inside and getting very little done, 

Ouch, that does not sound very nice at all.  I wish you a quick recovery :)

> so I hope you can maintain your patience. The project is very much not abandoned, and I think you will really like the refactor when it releases.

I didn't mean to sound like I thought the project was abandoned, sorry if it came across that way.  I very much appreciate what you've done here, so don't rush anything, we can wait!

**Comment by WisdomWolf** [comment]
FWIW You can do this currently by creating a tap-macro that calls a cmd and then executes the layer switch. Wrap that all up in a new alias and it's just as easy to use as any other button. Although now that I have typed all that I realize that I've only tested this for layer-switch and that layer-toggle might be slightly more complex. I'm planning to use a simple Python script to add an indicator to the panel (I use Ubuntu MATE) when layers are active.

**Comment by slotThe** [comment]
Closed via #146
