### ISSUE TITLE
Regular keys + TapHold in quick succession repeats the last previous key

### ISSUE THREAD

**Issue by terlar** [david-janssen/kmonad#26]
Hi, was recommended this project by a friend and I think it really looks promising. I am currently using 0.3.0. I see consistently key repeats when typing quickly.

With a binding like this:
```
@let = TH 200 ret lctl      // Return when tapped, control when held
@ret = TH 200 ret rctl      // Return when tapped, control when held
```

If I write `gs`, followed by holding the `@ret` or `@let` key I will see something like `gsss` up to `gsssss`. So somehow the holding of the key triggers as holding the previous key.

I see it very consistently. I have quite low "xkb repeat interval" set, so might influence this behavior as well, will try to configure it higher.
```
xkbRepeatDelay = 200;
xkbRepeatInterval = 33; # 30Hz
```

**Comment by david-janssen** [comment]
That is very strange. You are saying the key-repeat you are getting is caused by a different key altogether? As in: you get strange repeating 's' key behavior, but only when you use your `let` or `ret` keys? You are also sure you only get this strange behavior when using `kmonad`?

...
...

Wait a minute! I think I know what might be going on, and I'm afraid it's not a bug, it's a feature :-).
A tap-hold will pause all other processing of (and therefore output) of keys until it has decided what kind of key it will be. So if you press a taphold, nothing will happen until you either: release it, or the timer is up.

So what must be happening is this: you are typing really quickly, you press s, just before you release s you press `let`, then you release s. However, as long as you are holding `let` the s-release is held until `let` has decided. However, with such a short `xkbRepeatDelay` that small delay is enough for X to start repeating your key.

Simply making your `xkbRepeatDelay` should indeed solve the problem. Having the 200ms delay in your Tap-Hold's be of equal length or longer than your `xkbRepeatDelay` should be the issue here.

**Comment by terlar** [comment]
I don't think this is the case, if I don't press any of the let / ret keys, it never repeats like that. But when I press the let / ret key in quick succession of the keypresses it repeats the previous key.

I tried to press `g` several times, never repeating, but as soon as it is followed by the other keys it almost happen every time. The only explanation would be if the system normally detects this and drops such duplicated keys, but when using kmonad it does not. You mean the opposite? TH be shorter than repeat delay? Because if the repeat delay is any lower than 500ms and TH 170ms I see this.

**Comment by david-janssen** [comment]
I think we might be talking past each other, and rereading my previous message I can see the ambiguity, so here it is again, disambiguated:

Your `xkbRepeatDelay` should be significantly longer than your TapHold delay, because the TapHold will pause processing of any key events (like releases), which would then exceed your `xkbRepeatDelay`, causing linux to start emitting repeating keyevents.

Let me know if things work with a longer `xkbRepeatDelay` :-)

**Comment by terlar** [comment]
Okay, I see, it seems like it works even with `xkbRepeatDelay` of 200ms and TH of 170ms. 

I just found it odd that I didn't experience this before and also when using xcape.

So with the lower setting, I could reproduce every time by pressing one key quickly followed by the kmonad special key and holding that key, and it would produce that previous key consistently 2-4 times. If I didn't press the special kmonad key and just pressed the key once or followed by other normal keys this never happened.

But does that mean that if you at any time have a lower xkbRepeatDelay than the TapHold delay and press the special key quickly enough it is "designed" to not register the key event release until the TH decides it is a hold and not a tap and will thus when released produce as many repeats for that time until the hold was triggered. Because that is what it feels like to me.

So...
With `xkbRepeatDelay = 200`, `xkbRepeatInterval = 50`, `TH = 200`:
Key press of `g`
... 150ms later ...
Key press of `@ret` (hold detection starts/blocks key release events)
... 50ms later ...
Repeat delay kicks in (another `g`)
... 50ms later ...
Repeat interval (another `g`)
... 50ms later ...
Repeat interval (another `g`)
... 50ms later ...
Repeat interval (another `g`)
Hold detected (key events released)
...
Output of `ggggg`

Is this understanding correct? The more I think about it this would explain the behavior. Feel free to close again if this is the case.

**Comment by terlar** [comment]
Shouldn't the key release event for the previous key be triggered first though at the point `@ret` is pressed?

**Comment by david-janssen** [comment]
It is the second bit, where you are typing so fast that the release of `g` happens after you press the special key. (you can inspect this using `evtest` actually, just do an evtest grab of your keyboard, type something really quickly a few times, and see the ordering of events). And it is exactly as you describe it, and this was indeed something I designed intentionally. (Actually required a bit of a headache, because you have to store events, make a decision, roll back time, and rerun events).

The reason I did it this way is because of my experience with QMK, which doesn't do it this way, and I kept running into other issues when typing too quickly. Basically, if you use a TapHold to make a button that does a shift when held, I kept having to wait a lot of time (well, 200 ms, but when typing quickly that's a long time) before I could use the shift, and it really messed with my rhythm. The same with a TapHold that functions as a Control that you want to quickly use for keyboard shortcuts, having to pause for a button to switch to 'held' is a huge headache.

It might actually make sense to support both behaviors, and I do have a reworked `kmonad` that I still need to write a language parser for that should support either button-style. I currently don't have enough time to really sink into `kmonad`, but I hope to get a chance in a couple of weeks.
