### ISSUE TITLE
Emitting endless returns/enters when starting

### ISSUE THREAD

**Issue by kjs3** [david-janssen/kmonad#28]
Using [this config](https://gist.github.com/kjs3/a3472472d81feab7d4df5b3819b36ce2) for [this Das keyboard](https://www.daskeyboard.com/daskeyboard-4-professional-for-mac/)

Downloaded the latest release, made it executable and starting like this:

```
sudo ./kmonad-0.3.0-linux kmonad-das.kbd
```

Kmonad seems to start up fine with `Starting event loop` but that line quickly scrolls away. An endless loop of returns/newlines are being emitted and not just in that particular terminal. The whole system is receiving the key, it locks up the trackpad, etc.

Any idea what's going on here?

**Comment by kjs3** [comment]
Btw, this same thing happens with a different config I was trying to apply to the built-in keyboard on a Thinkpad x1 carbon (7th gen if that matters to anyone).

**Comment by david-janssen** [comment]
Hey there,

The power is out at the moment (sending this from laptop which doesn't have my dev environment setup, using mobile internet), so I can't test anything. However, I do have a sneaking suspicion. Could you try launching kmonad by using `sleep` first? Something like:

```sleep 2 && sudo kmonad kmonad-das.kbd```

Basically, I think `kmonad` is starting and capturing the release of your enter key that you pressed to launch kmonad. I thought I took measures to prevent this, but I can't check right now. The above way of launching kmonad should capture the release first, and only then start kmonad.

On a side-note: I strongly recommend not using `sudo` to start 3rd party programs (like kmonad). If you add yourself to the correct groups and make sure the `uinput` kernel module is loaded (`sudo modprobe uinput`), then you don't need `sudo` to launch `kmonad`.

Cheerio, let me know how it goes.

**Comment by kjs3** [comment]
@david-janssen That's exactly what the issue was. Fixed!

As far as using `sudo`, I've added the `uinput` group, added my user to it, and created a `50-uinput.rules` file in `/lib/udev/rules.d/` with the recommended rules.

```
KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
```

I still get a permission errors for both eventN and usb id files.

```
/dev/input/by-id/my-kbd-id: openFd: permission denied (Permission denied)
Encountered raw IO Exception attempting restart

...

/dev/input/event3: openFd: permission denied (Permission denied)
Encountered raw IO Exception attempting restart
```

**Comment by kjs3** [comment]
Fixed the permission error. 

`eventN` files are in the `input` group on my system (Manjaro). I just had to add myself to the `input` group too and everything works now. 

This is amazing! I finally have multiple keyboards, each mapped differently, simultaneously, and happening underneath the DE/window manager. :tada: 

Thank you for all the work on this.

**Comment by david-janssen** [comment]
Power is back! Happy to hear you figured out your issues :-).

**Comment by asheshambasta** [comment]
I'm sorry if I'm bringing up an old issue, but I've had no luck with this so far: I can cat the device file, which confirms that the permissions are correct; however; kmonad still reports a permission denied error:

```

╰─$ kmonad tutorial.kbd 
kmonad: /dev/uinput: openFd: permission denied (Permission denied)

```

Has something changed?

Also, all links seem to be broken since the repository seems to have moved under a different handle.

**Comment by 6gk** [comment]
> Also, all links seem to be broken since the repository seems to have moved under a different handle.

Yeah..  Creating `david-janssen/kmonad`after moving to the org might have broken a few things, as by default github can handle redirecting on repo rename/moves

**Comment by 6gk** [comment]
I don't know how github's rate limiting works, but I'm pretty sure that (if you want to fix the auto-redirect)

1. deleting `david-janssen/kmonad`
2. moving `kmonad/kmonad` -> `david-janssen/kmonad`
3. moving `david-janssen/kmonad` -> `kmonad/kmonad`

In that order should work.  Then people can use `git clone https://github.com/david-janssen/kmonad` and it'll download `https://github.com/kmonad/kmonad` instead of just a repo saying "hey please use kmonad/kmonad instead".

@david-janssen

**Comment by david-janssen** [comment]
@6gk Ahhhh, the reason I put up the redirect repo is because I noticed people were still starring my old repo, and I wanted to direct attention to the new kmonad. I'm not sure I understand: exactly what links are broken?

@asheshambasta The permission error is because you are trying to initialize a uinput keyboard, but I'm guessing you don't have uinput permissions. May I direct your attention to the first entry in the FAQ? https://github.com/kmonad/kmonad/blob/master/doc/faq.md

**Comment by asheshambasta** [comment]
@david-janssen I did get it to work between a series of reboots, thanks. I believe all I needed was a reboot and I was confused, my apologies.
As for the broken links, it seems like any referenced links in the issues here to issues from kmonad seem to refer to non-existent issues on the kmonad repo under your handle instead of under @kmonad itself. It isn't a huge inconvenience if you know you need to replace the handle with kmonad, but it may confuse some.

**Comment by 6gk** [comment]
> I'm not sure I understand: exactly what links are broken?

Practically anything automated that links to your repo - such as build scripts,

And links to specific files that expect the old url (practically anything written before a few days ago) will just get a 404 - such as https://github.com/david-janssen/kmonad/blob/master/src/KMonad/App.hs

**Comment by david-janssen** [comment]
> Practically anything automated that links to your repo - such as build scripts,

DOH!

**Comment by david-janssen** [comment]
> I believe all I needed was a reboot and I was confused, my apologies.

No need to apologize. If you ever encounter an issue you can't figure out I encourage you to come and ask for help :)

**Comment by david-janssen** [comment]
@6gk Actually, since I first moved kmonad to the new org by properly moving it with git (and then I make my own fork) I think the redirect worked, but then got overwritten by me forking my own copy. Just deleting my own copy seems to have worked. `git clone`ing the `david-janssen/kmonad` now seems to fetch `kmonad/kmonad` even though I don't have a `kmonad` repo under my name anymore.

**Comment by 6gk** [comment]
> Just deleting my own copy seems to have worked.
Nice.

> git cloneing the david-janssen/kmonad now seems to fetch kmonad/kmonad
even though I don't have a kmonad repo under my name anymore.

Neato, that redirecting is the intended behavior.

**Comment by 6gk** [comment]
Redirect seems to have broken since you re-made `david-janssen/kmonad-personal`, @david-janssen.  
I'm assuming that it made using the `david-janssen/kmonad` name, and you manually suffixed it with `-personal`?

For example: https://github.com/david-janssen/kmonad/issues/179 - I found this on google, and it redirects to david-janssen/kmonad-personal/issues/179 which is a 404.

I guess (hopefully?) moving kmonad/kmonad -> david-janssen/kmonad -> kmonad/kmonad *should* fix the redirects?

Damn, if only github had an easy redirect maker.

**Comment by david-janssen** [comment]
Whhhhyyyy github... WHHHHYYYYYY

Thanks for the heads up. I never notice these things.

**Comment by Myrdden** [comment]
Hiya, I'm wondering if it's totally accurate to say this has been resolved, as it doesn't appear to have actually been fixed by anything... Or, maybe the workaround counts as the fix? I'm not super familiar with protocol.

In any case, it would be lovely if the workaround here (using sleep) were to be placed somewhere visible, like the FAQ perhaps, as I've spent the last maybe two hours pulling my hair out trying to even figure out what is going on & how to phrase a search query before stumbling upon this ticket. (I'd been running it through it's systemd service, so all I was getting was the system locking up and the mouse flickering until I'd killed it)
