### ISSUE TITLE
Tap-hold behavior seems off in refactor branch

### ISSUE THREAD

**Issue by david-janssen** [david-janssen/kmonad#42]
Alright, I switched to the refactor branch and tried it out. The fallthrough seems to work great! Thanks a lot for doing this.

However, I noticed a problem that I'm not sure comes from refactor or just this change, which is preventing me from switching to refactor.

In the old docs, it says:
> The tap-hold pauses all event processing until it decides what kind of button it is, and then emits either the tap of its tap-button (when tapping) or the press of its hold button (when holding), with the release coming when the tap-hold is released again.

However, this does not seem to be the case anymore. If I press (and hold) a button with tap-hold, and then type characters (which are supposed to now be from a different layer) within the tap-hold delay, the characters from the base layer get emitted immediately.

Here is my layout for reference: https://github.com/theol0403/kmonad-layout/blob/master/refactor.kbd

_Originally posted by @theol0403 in https://github.com/david-janssen/kmonad/issues/41#issuecomment-662739621_

**Comment by david-janssen** [comment]
Thanks for the headsup, I will definitely have a look at this. Tap-holds work fine for me under refactor, so it'll require some investigation :-).

**Comment by thoelze1** [comment]
I'm having this issue too.

I had been using commit eb2b043 on refactor and tap-hold was fine. I just rebuilt from commit 4723570 on refactor, and now tap-hold behaves differently. So the change must come from one or more of the following commits:
- 4723570
- 1e12b44
- 9cb8a2c

**Comment by david-janssen** [comment]
Thanks for the headsup. It goes to the top of the pile.

**Comment by david-janssen** [comment]
Hey everyone,

Fixed in: bebf71dcf536bdc4f667815b6cbbde62330e17e2

Just mentioning quickly: @theol0403 and @obar, to ensure you guys get a notification.

Yep, you guys were right. Was a nincompoop. Added some functionality to support a new button, but forgot to test `tap-hold` correctly, because I was only using `tap-next` in my own config. `tap-hold` should work exactly like it did again.

Additionally, there is a new tap-holding button: `tap-hold-next`, that is a mixture between the other two.

`tap-hold`: Waits for a delay, and behaves like a hold once the delay is exceeded (rolling back events if necessary)
`tap-next`: Waits for next key, if it is release then tapping, if something else, then holding
`tap-hold-next`: Waits for a delay *or* the next key. If either the delay expires or we detect a different key, we switch to holding. If we detect a release within the delay, we behave as tapping.

I especially like `tap-hold-next` for buttons like my 'ctrl/enter'. It needs to be super quick, so tap-hold annoys me. However, when I use tap-next, sometimes I just press the button because my brain thinks it wants to press control, but then changes its mind. Now I am stuck holding a button that, on release, becomes an unwanted enter. With `tap-hold-next`, after the delay, it just becomes a ctrl anyways, and I don't have to go deleting enters.

**Comment by obar** [comment]
Thank you very much for this!

I really like the `tap-next`/`tap-hold-next` idea. Unfortunately as I mentioned in the duplicate of this issue: I get an overlap of keypresses when typing quickly so the next key event is the press of a key I don't want to modify, a problem when using this for home row mods. I suspect that triggering on the next key up (rather than whatever the next key event is) would solve this.

While the functions are all very clearly documented, I don't have a good enough grasp (read: any grasp) of the haskell syntax to try this out, so I'm asking for tangentially-related help in this thread. I think that a modified form for `a` as a roll-friendly-`tap-next`, emitting ether `t` or `h`, would need to use a potential next different key (`x`) press event in both cases of a condition. That condition would be the release of `a` (emit `t` followed optionally by `x` if it got pressed) or the release of `x` (emit `hx`).

I suppose one starts to get into edge cases (what if `x` is special, queuing [`x`, `y`, …] key presses during hold of `a` for bigger rolls) and I have no idea if the other code in the repo can/does account for it. Even ignoring those edge cases for a naive implementation of the above would be useful to try out, but if that is still too hairy of a request then please ignore :)

**Comment by thoelze1** [comment]
@obar thanks for bringing this up. I've wanted the same feature for a while (see #38) and it helps to know that others want it. Now that I've finished porting kmonad to mac, I'll see if I can implement this.

**Comment by obar** [comment]
I'm looking forward to it! In the meantime I'm enjoying a shorter reach for shift with this:

```
/sh (tap-hold-next 300 / rsft)
```
