### ISSUE TITLE
Idea: Community Repo to share configs for the refactor

### ISSUE THREAD

**Issue by joshskidmore** [david-janssen/kmonad#53]
Would you be open to a separate, community repo (similar to QMK's `keyboards/*/keymaps/*` directories)? It would potentially make it easier for people to jump in and get started, plus it could help get some default SRC layers for various keyboard types. Again, this would be community driven, but could be helpful.

**Comment by david-janssen** [comment]
I'd be very open to this. I didn't realize that's how the keymaps directory in QMK worked, I always just assumed they fielded a lot of pull-requests :-). I'll have a look at how to do this soon. Didn't even realize this was an option. Thanks for the good idea.

**Comment by david-janssen** [comment]
Hey Josh,

I had a quick look at this, because based on your message I thought they had implemented some kind of special mechanism to make this work. But based om my initial (5 minute) investigation, they do just field a lot of pull-requests. Am I incorrect?

If that is the case, I am actually still very open to it, because in the end I am not going to test user-configs, so any kind of user-config will just get looked over for obviously malicious stuff and then get approved. Not too much work at all. So, given that, I have 2 questions for you:

1. Is that, in your experience, also how things are organized in QMK?

2. What would be a good way of organizing this directory in KMonad? 

Info behind (2.): One big difference between KMonad and QMK is that our input-layers are actually very keyboard agnostic. You can take my atreus keymap, point it at a normal laptop keyboard, and everything would just work. The only important thing is that your `defsrc` lines up with your `deflayer`s, and then we just translate input to output. On the other hand, it might be really nice to sort configs by keyboard, just so you can figure out what keymaps people with similar keyboard use. Perhaps we make a 'generic-qwerty' category, and a 'generic-60%', etc.?

Anyways, let's brainstorm a little bit, and then I'll make the directories.

**Comment by david-janssen** [comment]
So, I gave this some thought, and created the `./keymap` layer. There we have a subdirectory `template` for input templates (already added a few) and a subdirectory `user`. If you want to include your keymap into kmonad please make a subdirectory in `user` matching your github username, and I'll approve those pull-requests.

This is currently only under the `refactor` branch, but I'll be merging that soon into `master`.
