### ISSUE TITLE
Print Screen, System Request codes

### ISSUE THREAD

**Issue by obar** [david-janssen/kmonad#59]
With the two keyboards I have to test, under Ubuntu 20.04, using `showkey` from the terminal, I don't actually get the Print button code from the Print Screen key—I get System Request. The OS translates this to Print (works in i3 key binding for example).

I tried putting `print` into the source and base layers of my kmonad config but it didn't work, that's how I realized this is happening. By replacing this with `sysrq` in both spots it works again. It also works by just replacing in the source, and having `sysrq` translate to `print` in kmonad.

I know that these two keys [have a historical link](https://en.wikipedia.org/wiki/System_request) but I don't have enough keyboards to test. If this key code is being sent in the same way across all keyboards (I suspect not), it might be worth aliasing the keycodes differently for the source layer. If it's not consistent, maybe a note about this behavior in the documentation would be worthwhile? Or maybe this issue is enough of a heads up :)

If anyone reading this has a print screen button to test with, please share your experience. Starting kmonad with `-l debug` will show relevant codes received. I've tried with a Microsoft Sculpt and a cheap Microsoft Digital Media Pro keyboard.

**Comment by david-janssen** [comment]
Hey @obar,

That's actually quite interesting, I had no idea. The `Keycode` ADT in KMonad is just a near copy-paste of the Linux event-codes, which you can find here:

https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

They list SysRq as 99, and Print as 210, with a note saying "AC Print". I think adding a note to documentation explaining that print screen is not actually `print` but `sysrq` is not a bad idea, we could also add an alias like `pscr` and `printscreen`.  I, however, do not want to stop referring to `Print` as `print`, because I do want to stick as closely to the original linux specification as possible.

Wanna have a go at adding some documentation? If not, I can have a go later this week

**Comment by david-janssen** [comment]
Referenced in: d6ca14b7f527cfff60a6f1502602b6369e50d5a4
