### ISSUE TITLE
[Linux] Bug: using fn key on apple keyboard crashes kmonad

### ISSUE THREAD

**Issue by thoelze1** [david-janssen/kmonad#72]
I'm running a fresh build of `master` under Debian on a MacBookPro12,1 with `-l debug`. Pressing <kbd>fn</kbd> on the builtin keyboard crashes kmonad with the following output:

```
Closing process: emitter_proc
Closing KeySource
Releasing ioctl grab
Closing KeySink
Unregistering Uinput device
Closing Uinput device file
kmonad: toEnum{Keycode}: tag (464) is outside of enumeration's range (0,255)
CallStack (from HasCallStack):
  error, called at src/KMonad/Keyboard/Keycode.hs:312:32 in kmonad-0.4-I8ZsE4oWg3dF5zI18fnym4:KMonad.Keyboard.Keycode
```

Has anyone else experienced this issue yet? Maybe @eighal?

**Comment by eighal** [comment]
> Maybe @eighal?

Yes, same here.  (It prints that call stack for me even without `-l debug`.)

**Comment by david-janssen** [comment]
So, looking at that it seems to indicate to me that the Macbook keyboard hardware is sending a key-event to KMonad that we had never anticipated, i.e. with an unparseable keycode.

I'm guessing `evtest` would also show some kind of keycode that is above 255?

The solution would probably be to add support for arbitrary int-values above the expected keycodes, perhaps define an event's keycode value as 'Either Keycode Int', (the alternative: expanding the Keycode to cover this 464 value, would mean losing correspondence between Keycode and 'real' linux-kernel keycode values.

A bit too tired to come up with the optimal solution right now, but if you guys can gather a bit more data, it sounds like a clear and solveable problem.

**Comment by david-janssen** [comment]
Of course, the ultimate upside of this is that we should probably be able to rebind the Fn key now :-)

**Comment by eighal** [comment]
Yes!  Since it is a small keyboard (although no Atreus), that is really good news.

**Comment by eighal** [comment]
> I'm guessing `evtest` would also show some kind of keycode that is above 255?

Yes: I get 464.

**Comment by david-janssen** [comment]
Very good, I'll need to do a bit of refactoring of the core of KMonad to make this work, we need to change how we represent keycodes. Luckily: this is Haskell :-). Super busy atm, so might not get to it soon though. Is there a way for you to ignore that key? Otherwise it might be quite easy to just hack an 'ignore-crash' thing into keycodes as a temporary duct-tape fix.

**Comment by eighal** [comment]
Speaking for myself only: it's in the corner of the keyboard and it's easy to just not press it.

> I'll need to do a bit of refactoring

In Haskell you have to refactor to add 1 to a global constant, don't you?  :-P

**Comment by david-janssen** [comment]
Global... What is this global you speak of? :P 

But what I was referring to was that in Haskell it's super easy to change the underlying data-representation. As long as you line up how you map into and out of your representation, the type-checker usually helps you 95% of the way there.

**Comment by eighal** [comment]
> Global... What is this global you speak of? :P

Ha!  Touché!

> But what I was referring to was that in Haskell it's super easy to change the underlying data-representation. As long as you line up how you map into and out of your representation, the type-checker usually helps you 95% of the way there.

Yes of course.  And this is a good opportunity for me to say how much I like your code base, and especially the fact that it's well commented.  (Sadly, I'm not a Haskell programmer, but I know enough other languages to have an opinion about your coding style anyway!)

**Comment by david-janssen** [comment]
So, I have a 'working' solution with a huge caveat. I started doing a big refactor of how we organize 'Keycodes' on the airplane. At the time I was stoned off my rocker on strong antihistamines, so I'm amazed that the code seemed to make sense when I looked at it just now. I had to do a little bit of cleaning and update the parsers, but basically there is now a  slightly outdated KMonad with this feature added in. It isn't tested beyond me running `kmonad keymap/user/david-janssen/testing.kbd` so you'll be my guineapigs (haven't got an apple keyboard).

If this works for you guys, I'll make the effort to merge this branch into master cleanly. Anyways, here's the ref: 731bda0

Beyond the fact that the internals changed a *lot*, the only things that changed in the configuration is that I might've lost some aliases (I can run the 'tutorial.kbd' but haven't ported all the aliases over yet) aaaaand, there is now this syntax (liable to change, just to test):
```
(defsrc 
  a &123 &464)
(deflayer example 
  &321 b z)
```

So, to explain, `&xxx` just defines a literal keycode based on the number. It's a bit finicky for now, but if you can find the integer representation of a keycode (for example via `evtest`) you should be able to both capture it by using it in the `defsrc` and emit it by putting it in a `deflayer` (that second one was an unexpected bonus, because anything that evaluates to a keycode evaluates to a button that emits that keycode, and so without even intending, that just worked out of the box).

So, if you could try both remapping `Fn` to some arbitrary key, and remapping some arbitrary key to `Fn`, that would be great. If this sort of works, I'll make the effort to merge it nicely into master.

**Comment by david-janssen** [comment]
Oh, and I should mention, KMonad will try to parse a literal keycode before trying a named keycode, so you can just refer to `q` as `&16` for example. All the named keycodes should still be literally-referable

**Comment by david-janssen** [comment]
Oh, and I should *also* mention, this commit will only compile under Linux. Will definitely make it work for Windows and Mac too, though, but I moved from 'everything internally is represented as Linux, and we map into and out of that representation' to 'OS-specific code defines its own Keycode representation that has to conform to some API'. I still have to implement the Windows and Mac Keycodes

**Comment by eighal** [comment]
Works for me, in both directions.  You're a star!

**Comment by eighal** [comment]
> so you'll be my guineapigs

I tried to interest my actual guinea pigs, but they ran away.

**Comment by MaxGyver83** [comment]
For me, it's the first time to compile Haskell code. I just have installed stack and now I'm running `stack build`. It has been running for a while, now. I'll come back here later.

**Comment by david-janssen** [comment]
Hey @MaxGyver83,

Yeah, the first time you compile it will make you compile aaaaalllll of the libraries that we depend on, which is quite a bit. Any future recompilation should take no more than 10-20 seconds.

**Comment by MaxGyver83** [comment]
OK, all compiling finished and I tested it:

- Mapping `&464` to `z` works: `Fn` emits a `z` but it's still working as `Fn`.
- Mapping `t` to `&464` doesn't do anything. But I think that's as expected because `Fn` combinations are processed in the keyboard's firmware. So that key event `&464` emitted by KMonad can't be "seen" by my keyboard.
- If I don't map `&464` at all, KMonad doesn't crash either.

Great! This fixes the bug and improves KMonad!

**Comment by david-janssen** [comment]
Then since both guineapigs survived and approve, I proclaim this issue: Resolved!

**Comment by Vermoot** [comment]
Has this ever been merged into master? Fn key on a macbook is still an issue, even though this seems to have been solved here.

**Comment by ildar130** [comment]
@david-janssen, as I understood from [your comment](https://github.com/kmonad/kmonad/issues/72#issuecomment-688617271), expanding the Keycode to cover 464 value is a bad idea. Does it have something to do with compatibility with non-Linux OSes?
I'm asking because I tried it and it solves the problem, at least on my two PCs (both on Ubuntu).
And also seems like codes above 255 are defined in Linux kernel. See [here](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h), line
`#define KEY_FN			0x1d0`
(0x1d0 == 464).

**Comment by ZerdoX-x** [comment]
ready! 🥳
