### ISSUE TITLE
Cannot submit to hackage

### ISSUE THREAD

**Issue by david-janssen** [david-janssen/kmonad#75]
@thoelze1 

Hey Tanner, was about to put this in the MacOS support thread, but thought I'd start a new issue. I've been taking steps to submit `kmonad` to Hackage as a package (to facilitate inclusion of `kmonad` in `nixpkgs`). It is currently breaking on the fact that we have this git submodule with the Karabiner extension. Is it necessary to include this submodule in the `kmonad` source? I.e. could we have an installer script that makes sure that the extension is installed, or do we need to ship it with `kmonad`?

Cheers, D

**Comment by david-janssen** [comment]
So I fixed this by removing the `include-dirs` entry for karabiner elements from the cabal-file. This means building under Mac now requires you to manually include the include-dir in the path. This might mean that building automatically from hackage might not work for Mac, but I don't think that would've worked anyways, because you needed to install the `kext` in the first place.

**Comment by thoelze1** [comment]
I replaced the now-commented `include-dirs` lines in the cabal-file with the `--extra-include-dirs` parameter in the `stack` invocation in the Mac section of the docs (I'll PR soon). This `--extra-include-dirs` parameter also works with `cabal install` which means that Mac users may be able to install via Hackage (which I haven't attempted) as long as they have the kext installed first.

I could remove the kext submodule and instead provide installation instructions and/or an installer script. I suppose the kext does not need to be shipped with kmonad, though I think it makes installation that much quicker for first time kmonad users. An installer script could also make for easy installation without a submodule, but seems like an equivalent solution (possibly with added complexity). I'm fine with leaving the kext as a submodule unless there's a reason not to. I should also note that I am planning on adding a "driver extension" (dext) as a submodule in order to support the upcoming macOS release.

**Comment by david-janssen** [comment]
Hey @thoelze1, thanks for the update. I think leaving the `kext` in for now is probably not an issue Mac users still need to explicitly clone KMonad recursively, and it is very well hidden (not cluttering up the directory structure at all) so let's just leave it as it is. I eagerly await your PRs.

Cheers, D
