### ISSUE TITLE
Multiple dependent layers (as in the Neo keyboard layout)

### ISSUE THREAD

**Issue by MaxGyver83** [david-janssen/kmonad#77]
I'm trying to implement my personal keyboard layout that was derived from the [Neo layout](https://www.neo-layout.org/). (Later I want to implement Neo and other layouts derived from it, too.)

All these layout have in common that the use 6 layers. For obvious reasons we can't use 5 modifiers on each side (at least on a standard keyboard). So we have to combine modifiers for the layers 5 and 6.

You can reach the layers by holding these modifiers:

| Layer     | Modifiers    | Keys |
| --------|---------|-------|
| 1  | (None)   | (None)   |
| 2 | M2 | `Shift`    |
| 3 | M3 | `CapsLock` or `#` (= `\` on a US keyboard)    |
| 4 | M4 | `AltGr` or `<` (= `Key102nd`, not available on a US keyboard)    |
| 5 | M2 + M3 | see above |
| 6 | M4 + M3 | see above |

This seems to be easy to realize in KMonad (not yet complete but you should get an idea how it works):

```lisp
(defsrc
  grv       1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab       q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps      a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft 102d z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt rmet cmp  rctl
)

(deflayer vou-wide
  tab         1    2    3    4    5    6    7    8    9    0    -    =    bspc
  lmet        v    .    o    u    ä    ´    k    g    l    h    f    j    @lvl3
  @lvl3       c    a    e    i    y    ß    b    t    r    n    s    ret
  @lvl2 @lvl4 z    x    ,    ü    ö    q    p    d    w    m    @lvl2
  lmet lalt lctl           spc            @lvl4 rmet @sym @tst
)

(deflayer level2
;;  tab         °    §    ℓ    »    «    $    €    „    “    ”    —    ¸    bspc
  tab         1    2    3    4    5    6    7    8    9    0    -    =    bspc
  lmet        V    •    O    U    Ä    ´    K    G    L    H    F    J    @lvl5
  @lvl5       C    A    E    I    Y    ß    B    T    R    N    S    ret
  @lvl2 @lvl4 Z    X    -    ü    Ö    Q    P    D    W    M    @lvl2
  lmet lalt lctl           spc            @lvl4 rmet @sym @tst
)

(deflayer level3
  _           ¹    ²    ³    ›    ‹    ¢    ¥    ‚    ‘    ’    _    _    _
  _           @    %    {    }    ^    /    !    <    >    =    &    €    _
  _           |    `    \(   \)   *    →    ?    /    :    -    \_   _
  @lvl5 @lvl6 #    [    ]    ~    $    ;    +    "    '    \    @lvl5
  _     _    _              _              @lvl6    _    _    _
)

(deflayer level4
  _     ¹    ²    ³    ›    ‹    ¢    ¥    ‚    ‘    ’    _    _    _
  _     pgup pgdn up   bspc del  /    !    7    8    9    &    €    _
  @lvl6 home lft  down rght end  →    ?    4    5    6    _    @lvl6
  _ XX  ins  tab  ret  esc  _    ;    +    1    2    3    _
  _     _    _              0              _    _    _    _
)

(deflayer level5
  _     ₁    ₂    ₃    ♀    ♂    ⚥    ϰ    ⟨    ⟩    ₀    ‑    _    _
  _     θ    ϑ    ο    ϱ    η    _    κ    γ    λ    ψ    φ    θ    _
  _     χ    α    ε    ι    υ    ς    β    τ    ρ    ν    σ    _
  _ XX  ζ    ξ    ϱ    π    ϵ    ϕ    π    δ    ω    μ    _
  _    _    _              _              _    _    _    _
)

(deflayer level6
  _     ¬    ∨    ∧    ⊥    ∡    ∥    →    ∞    _    ∅    ­    ¯    _
  _     √    ↦    ∈    ⊂    ℵ    ˘    ×    Γ    Λ    Ψ    Φ    Θ    _
  _     ℂ    ∀    ∃    _    ∇    _    ⇐    ∂    ℝ    ℕ    Σ   _
  _ XX  ℤ    Ξ    ⇒    ∪    ∩    ℚ    Π    Δ    Ω    _    _
  _    _    _              _              _    _    _    _
)

(defalias
  lvl2 (layer-toggle level2)  ;; Bind lvl2 to a button that switches to a layer
  lvl3 (layer-toggle level3)  ;; Bind lvl3 to a button that switches to a layer
  lvl4 (layer-toggle level4)  ;; Bind lvl4 to a button that switches to a layer
  lvl5 (layer-toggle level5)  ;; Bind lvl5 to a button that switches to a layer
  lvl6 (layer-toggle level6)  ;; Bind lvl6 to a button that switches to a layer
)
```

But there is an issue:

* I have to define layer 2 (the shift layer) explicitly in order to map layer 5 onto the Mod3 keys. When I do so, the letters don't get shifted automatically, so I defined all capital letters explicitly. Apparently the `Ä` is not a problem but the `Ü` is:

```
kmonad-0.4.1-linux: Parse error at 241:31:
    |
241 |   @lvl2  @lvl4 Z    X    –    Ü    Ö    Q    P    D    W    M    @lvl2
    |                               ^
unexpected 'Ü'
expecting ')'
```

Same for the symbol `ℓ` in layer 2 (line commented out) or `χ` in layer 5.

Why?

Other questions:

1.  Can I somehow "fallthrough" the shift behaviour just for all letters? I want to redefine the number keys and the M3 keys in layer 2 but it would be nice if all letters could be capitalized automatically (like when I don't define a layer 2).

2. How can I make tab a "backwards" tab on layer 2 (like in QWERTY). There is no keycode for that. (The answer to question 1 could solve this problem, too.) Do I need a macro sending shift and tab, otherwise?

**Comment by david-janssen** [comment]
Hey Max,

So, the issue here is that you are trying to do something that 'sort of' exceeds the scope of KMonad. I will take a moment to explain what that is, why it exceeds the scope, how we still 'sort of' support it, and what you can do to make it work as well as possible.

# What you are doing and why it exceeds scope
You are trying to get KMonad to emit special characters. Perfectly understandable, support for those seems to be present already. However it is important to realize we never actually 'emit a special character', because such a thing is not possible, since keycodes are very limited and don't cover special characters like `Ö`. When you see `Ö` in the config, this is actually just syntactic sugar for a keyboard macro, so when you push that button, KMonad emits `compose shifted-' O`.

# Why we still 'sort of' support special characters
Turns out that the X11 compose-key sequences are semi-standard, they are available on basically all of Linux, and there are at least open-source solutions for Windows, and they all map at least some of the same sequences to most of the commonly used special characters.

# What you can do get near perfect support
So, since there is no such thing as a 'Keyevent for `Ö`', this will always fall outside of the true scope of KMonad. However, 'making it as easy as possible to make your keyboard emit what you want' is exactly the scope of KMonad, so you can actually get quite close to the desired behavior. Essentially, you can make KMonad emit any kind of key-macro you want at the press of a button, now you have to instruct X11 (you are on Linux, right? otherwise this whole section doesn't work) to interpret those macros as special character. For that, X11 provides the `~/.XCompose` file (NOTE: case sensitive.. not ~/.Xcompose.. 10 minutes of my life I'm not getting back :-S). I'll trust you to google the specific syntax and figure it out, but I got my keyboard to emit `⚥` by doing this:

`.XCompose`
```
include "%L"   # To include the defaults as well

<Multi_key> <0> <a>                 : "⚥"

```

`keymap.kbd`
```
(defalias 
  ⚥ #(ralt a 0)  ;; ralt should be whatever button you are using for 'Multi_key'
)

(deflayer ...
    @⚥ ....
)
```

# What I will do in the future
So, this is going to be a bit of work. You're going to have to manually define a compose-key sequence for any special character for which such a sequence does not yet exist. Then you're going to have to define an alias for each of those sequences and unalias them again in your keymap. Boilerplate, blergh...

I think I will write a parser that can read the `.XCompose` syntax figure out the bindings on the local system (that also gets us away from the assumed default bindings for en_us). That way you only have to define these bindings once (for X11) and KMonad can just piggy-back on that definition. However, I'm going to move continents on Tuesday, so I might not get to this in a bit :-).

# Oh, and finally
Yep, the `Ü` was just missing. Added in  b7214c4bfa7ae2d6d8ea99fd991aeb3b951fdb5a

**Comment by david-janssen** [comment]
Oh, and you have more questions:

Fallthrough-shift: not currently supported, and also not planned. Layers don't interact in KMonad, i.e. you can catch the input event coming from the OS, but to do 'fallthrough shift' you'd have to catch the output event of *another layer* and then decide to shift it. I've had people talk about stuff like this, so I'll ponder this for a bit and see what I come up with.

2. Backwards tab, not sure exactly what that is, but yeah `S-tab` should just get you a shifted tab without issue.

**Comment by MaxGyver83** [comment]
> you are on Linux, right?

Yes!

> However, 'making it as easy as possible to make your keyboard emit what you want' is exactly the scope of KMonad, so you can actually get quite close to the desired behavior. Essentially, you can make KMonad emit any kind of key-macro you want at the press of a button, now you have to instruct X11 (you are on Linux, right? otherwise this whole section doesn't work) to interpret those macros as special character. For that, X11 provides the `~/.XCompose` file (NOTE: case sensitive.. not `~/.Xcompose`.. 10 minutes of my life I'm not getting back :-S). I'll trust you to google the specific syntax and figure it out, but I got my keyboard to emit ⚥ by doing this: ...

Thanks! That's good to know. So regarding these special unicode characters, the layout definiton seems to be easier in XKB. They have names for almost everything, like `Greek_chi`. And if there is no name, you can write `U2011` for getting a unicode character by its code point.
Actually I don't use layers 5 and 6 at all, so I'll leave that tedious work for somebody who really wants to use these characters.

> Fallthrough-shift: not currently supported, and also not planned. Layers don't interact in KMonad, i.e. you can catch the input event coming from the OS, but to do 'fallthrough shift' you'd have to catch the output event of another layer and then decide to shift it. I've had people talk about stuff like this, so I'll ponder this for a bit and see what I come up with.

No problem, it's just a matter of comfort when I define a layout or someone wants to swap some letters. If they forget to swap letters on layer 2, they will notice quickly ;-)

> Backwards tab, not sure exactly what that is, but yeah S-tab should just get you a shifted tab without issue.

XKB calls it `ISO_Left_Tab`. No problem, I'll just send a shift + a tab.

**Comment by MaxGyver83** [comment]
@david-janssen , this might be interesting for you: I maintain (a fork of) a Windows keyboard driver for Neo and other (similar) keyboard layouts: [neo2-llkh](https://github.com/MaxGyver83/neo2-llkh). This works fine but lacks many of KMonad's cool features.

`neo2-llkh` uses [SendInput](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) (from `winuser.h`) for [sending Unicode characters](https://github.com/MaxGyver83/neo2-llkh/blob/6b211ff75760438e147c2b196f68904610debc84/src/main.c#L482) not available in the current keyboard layout. Maybe you can use that function in KMonad (for Windows), too. That way, Windows users don't depend on a third party tool (*WinCompose*).

**Comment by david-janssen** [comment]
@MaxGyver83: That is certainly of interest. I hadn't realized you could inject UTF8 directly into Windows through SendInput, which is also exactly what we use. When I first hacked it all together it was Linux only, and I was only representing basic Latin1 Keycodes, and I never even considered that fact. This is very useful.

Practically speaking, this will require a bit of a redesign of certain core systems, but I had already started on that anyway (the original concept of a `Keycode` was flawed, and very Linux-centric). As you might have noticed already, things are a bit hectic here, so I don't know when I'll get to it, but it goes to the top of my pile.
