### ISSUE TITLE
Replace a + e with ä

### ISSUE THREAD

**Issue by MaxGyver83** [david-janssen/kmonad#78]
Can I somehow send an `ä` when I press first `a` then `e` by either holding back `a` until the next key is pressed (maybe even within a timeout) or by sending backspace + `ä` if an `e` is pressed after `a`?

Like `inoremap ae = ä` in vim.

The best I can imagine so far:

1. Map `a` + a one shot layer to the `A` key.
2. The one shot layer consists of only `_` except for the location of `e`.
3. The `e` key in that layer is mapped to a new key that sends backspace + `ä`.

But this is rather complicated. Am I missing an easier solution? Or are there already plans for this functionality?

**Comment by david-janssen** [comment]
Have you looked at the `tap-hold` functionality in the `tutorial.kbd`? There are a number of different buttons that do exactly what I think you're looking for, with ever so slightly different 'tap-detection' algorithms.

**Comment by MaxGyver83** [comment]
Of course I have checked the tutorial. I was rather looking for something like a [combo](https://beta.docs.qmk.fm/using-qmk/software-features/feature_combo). But I think I can get used to `tap-hold`.

If anybody wants to do the same:

```lisp
(defalias
  a (tap-hold 200 a ä)
)
```

And then in the layer definiton `@a` instead of `a`.

@david-janssen : The `tap-hold-next-release` function is really awesome! I use it now for having `Ctrl` and other modifiers in the home row!

**Comment by david-janssen** [comment]
Aaahh, those combos look nifty. They're basically like a tap-hold but the ordering doesn't matter, right? Like `ae` or `ea` in the same  time-span would always produce an `ä`. That would be rather hard to implement in KMonad at the moment, since buttons exist in complete isolation. I have some ideas, but the are very 'someday'-ish.

In regards to `tap-hold-next-release`, yeah, it's really great. Not my idea though. Had some users come up with it and then we managed to make it work. It's really comfy for typing quickly. All credit goes to community :D

**Comment by MaxGyver83** [comment]
> They're basically like a tap-hold but the ordering doesn't matter, right? Like `ae` or `ea` in the same time-span would always produce an `ä`.

I would even prefer if the ordering matters because `ea` appears in words like `appears` and should not be replaced. But unlike `tap-hold` this function wouldn't need any keys being held down.

**Comment by MaxGyver83** [comment]
I would like to support you with pull requests but I don't know anything about Haskell (apart from what I've read in a tutorial today).
