### ISSUE TITLE
[Mac] Illegal hardware instruction

### ISSUE THREAD

**Issue by agile-jordi** [david-janssen/kmonad#86]
When I run kmonad I immediately get an error:

```
$> kmonad tutorial.kbd -l debug

Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
IOServiceOpen error: e00002c2
IORegistryEntryCreateCFProperty error
[1]    44481 illegal hardware instruction
```

- My keyboard is my macbook's built in keyboard, product "Apple Internal Keyboard / Trackpad" acording to Karabiner event viewer. 
- My macOS is version 10.14.6
- I tried master by fixing `KeyKpenter` by hand. I also tried develop (`a2f2321`) with no luck either
- I'm just trying to use the tutorial keymap with this setup in defcfg:

```
  input  (iokit-name)
  output (kext)
```

Thanks in advance!

**Comment by thoelze1** [comment]
Hey! Right now, kmonad has to run with root privileges on Mac. There used to be a section in the docs explaining why, but it seems to be missing after the recent overhaul (thanks for bringing this to my attention). You can see the section [here](https://github.com/thoelze1/kmonad/blob/refactor/doc/syntax_guide.md) in my fork but the relevant bit is:

> Under Mac, KMonad installs a callback for each of the specified keyboards. Each callback triggers whenever new input is available from its associated keyboard.
> 
> Note that capturing key events and stopping them in order to send modified events [requires root privilege](https://developer.apple.com/library/archive/technotes/tn2187/_index.html#//apple_ref/doc/uid/DTS10004224-CH1-DontLinkElementID_10). In the future, privilege separation may be implemented so that just a small part of KMonad requires root privilege to run.

I haven't had the motivation to implement privilege separation, so I just run kmonad under `sudo`. Does this fix your issue? Let me know how it goes.

(I'll tag @david-janssen so that he sees the part above about the missing documentation)

**Comment by david-janssen** [comment]
Oops, I must've deleted this from the documentation during the recent version update. So sorry, will fix today. I'll leave this open until you confirm things work with `sudo`

**Comment by agile-jordi** [comment]
Thank you for your help!
Unfortunately I had no luck with `sudo` either. Still the very same output. I just tried today's master branch (2340c8dc3b635bfc173deed74dfb651b3a25f8da) and develop (a2f232137cf8ff671c09a5a32d982d253d08ae53).
Just in case, when switching versions, I do `stack clean` and then `stack install` as I'm not sure what `install` may be caching.

**Comment by agile-jordi** [comment]
I now tried rebooting with no luck either. 

Then I realized even if I quit karabiner-elements (which I use and intend to replace with kmonad), 4 processes with "karabiner" in its name were still running. I tried to kill them but they kept reapearing (I guess I didn't kill the right one first). So I tried uninstalling karabiner for the sake of testing.
Assuming I may have uninstalled the kext (not that I actually know how that works) I also installed it acording to the installation notes in develop.

But I still get a similar error message:

```
Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
Launching process: emitter_proc
IORegistryEntryCreateCFProperty error
```

Notice there is now "launching process", which wasn't there before. Also, there is no "IOServiceOpen error".

Hope that helps diagnosing what is going on here...

**Comment by thoelze1** [comment]
Thank you very much for the detailed reports. I've been occupied with other things but tomorrow I will try to figure out what's going on. I'll reply once I've had a look.

**Comment by david-janssen** [comment]
So, I won't be able to help out in great detail, because this is a Mac issue, but I'm just popping my head in to indicate that since the process now goes past `Opening IOKit` and into starting the emitting-thread, that at least the `IOKit` opening should be happening without issue. After the emitting thread is up, it moves on to trying to set up the `(kext)`. I wish you both the best of luck.

**Comment by thoelze1** [comment]
It turns out there are some unresolved issues going on with the Mac code at the moment (I've been distro-hopping for a couple of weeks and so I haven't been testing kmonad on Mac). I don't think they're the root of the issue but I'm sure they're not helping. I'll submit a PR or two with fixes for those issues.

As for your specific issue, try running this:

```BASH
cd c_src/mac/Karabiner-VirtualHIDDevice/example
make
virtual_keyboard_example/a.out
```

This will simulate some key events using the kext (first it will type abcDE, then it will open system preferences, then it will minimize all windows so that the desktop is visible). This will be a simple test that the kext is working properly. If you get issues running that, then I think we should file an issue upstream at [Karabiner-VirtualHIDDevice](https://github.com/pqrs-org/Karabiner-VirtualHIDDevice). Let me know what happens when you try that out!

**Comment by agile-jordi** [comment]
Thank you for your time on this!

I was able to run what you said and it seems it worked:

```
org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext
Checking virtual_hid_keyboard is ready...
virtual_hid_keyboard is ready.
abcDEEEEEEE
press control-c to quit
......................^C
```

It also typed some shortcut that moved my windows around :-). I hit ^C after a while.

Hope that helps.

**Comment by thoelze1** [comment]
You're welcome :)

So based on your information from the event viewer (you noted that one device lacks the manufacturer/product attributes), I think that the `IORegistryEntryCreateCFProperty error` may be harmless. In your [comment](https://github.com/david-janssen/kmonad/issues/86#issuecomment-694986903) above, what happens after the debugging information (ending in `IORegistryEntryCreateCFProperty error`) is printed? Do you still get an illegal hardware instruction error? Did kmonad crash? If not, maybe kmonad was working - you could try adjusting the tutorial config to check...

**Comment by agile-jordi** [comment]
Found it! 💃🏻🕺🏻🎊🎉

Not that I know what I'm doing in C++ land, but, after adding traces everywhere I found out that the program halted here: https://github.com/david-janssen/kmonad/blob/master/c_src/mac/keyio_mac.cpp#L84. It seems we are trying to CFRelease a NULL.

I just commented that line out and now it runs. Now it's time I actually learn what that example configuration is about and how does kmonad actually work. :-)

Thank you very much for your time! Its just commenting out a line, but let me know if I may help you somehow so that the fix reaches master whenever possible.

**Comment by thoelze1** [comment]
Woohoo!!! Nicely done. Thanks for finding that bug!

One more question: do you happen to know what version of Karabiner-Elements you were running before you manually installed the kext? (I'm wondering if an unforeseen version incompatibility caused the IOServiceError we saw in your initial comment...)

**Comment by agile-jordi** [comment]
> One more question: do you happen to know what version of Karabiner-Elements you were running before you manually installed the kext? (I'm wondering if an unforeseen version incompatibility caused the IOServiceError we saw in your initial comment...)

In case it is still of your interest, it is 12.10.0.

**Comment by thoelze1** [comment]
Is that the version that you had installed before uninstalling and reinstalling?

**Comment by agile-jordi** [comment]
Ouch. True, I actually don't know. Sorry about that.

**Comment by thoelze1** [comment]
@agile-jordi Have things continued to work? Can this issue be closed?

**Comment by agile-jordi** [comment]
Indeed! It now starts properly. I have some unrelated issue with my iso key, but I'm looking into it and it would be another issue, in case I don't figure it out.
Thanks again for your amazing work on kmonad!

**Comment by thoelze1** [comment]
Somewhere down the line, I [hardcoded](https://github.com/david-janssen/kmonad/blob/9a2a8a81a70a830261da36c432469f52da22aee8/c_src/mac/keyio_mac.cpp#L304) the US English keyboard code into the initialization of the kext...

Let me know if this is causing any trouble (if so, you could try commenting it or replacing it with the [correct country code](https://docs.oracle.com/cd/E25749_01/E25745/html/Clients-Keyboard-Country-Codes.html))

**Comment by agile-jordi** [comment]
I just created https://github.com/david-janssen/kmonad/issues/106 for the issue now that I have more info on that with the hope that we can close this one now that the original issue is solved.
